### ISSUE TITLE
image_view sometimes ignores autosize parameter

### ISSUE THREAD

**Issue by ahendrix** [ros-perception/image_pipeline#10]
When launching the image_view node with autosize=true, sometimes it
 displays resize handles and allows resizing, and sometimes it does not.

 When using a window manager where the resize handles have non-zero size
 (such as fluxbox), this is annoying.

To reproduce:
1) run fluxbox or another window manager that shows resize handles (I haven't tested with gnome/metacity or KDE)
2) roscore
3) roslaunch openni_launch openni.launch
4) rosrun nodelet nodelet standalone image_proc/crop_decimate camera:=/camera/rgb _decimation_x:=2 _decimation_y:=2
5) while sleep 1; do rosrun image_view  image_view image:=/camera_out/image_raw _autosize:=True ; done
6) repeatedly kill image_view; observe that sometimes it has resize handles and allows resizing, and sometimes does not.

**Comment by vrabaud** [comment]
I've tried 20 times and could never see any window handle (on Kubuntu 12.04) so it seems fine on my hand. Could it be a fluxbox bug ?

**Comment by GeeF** [comment]
The parameters don't work for me at all. I also tried window_name with the same result. Anything I don't see?
On Ubuntu 12.04/groovy

**Comment by vrabaud** [comment]
It works for me. They are private parameters, did you forget the underscore ?

```
rosrun image_view image_view image:=/camera/rgb/image_color _autosize:=True _window_name:="foo"
```

**Comment by GeeF** [comment]
@vrabaud Indeed. I didn't realize they were private. Thanks :)

**Comment by vrabaud** [comment]
cool. Closing for now. @ahendrix , please re-open if you are still facing that.
