### ISSUE TITLE
stereo calibration crash at epipolar_error

### ISSUE THREAD

**Issue by versatran01** [ros-perception/image_pipeline#100]
image_pipeline / camera_calibration / src / camera_calibration / calibrator.py
line 1015
epierror = self.epipolar_error(lundistorted, rundistorted, lboard)

The stereo calibration will crash at this line and says epipolar_error takes 3 arguments but 4 given.
I think it can be fixed by removing the last argument lboard.

**Comment by vrabaud** [comment]
#99  actually fixes that. thx.
