### ISSUE TITLE
image_view freezes after a few seconds.

### ISSUE THREAD

**Issue by kmhallen** [ros-perception/image_pipeline#101]
A single window freezes after an average of one minute. With half CPU usage or several image_view windows, the freeze happens after a few seconds.

ROS Answers question: http://answers.ros.org/question/193876/image_view-freeze-after-3-seconds/

This issue is present in releases 1.12.6 to 1.12.10 starting from commit a6e15e7, removal of GTK.

indigo, trusty, amd64

**Comment by vrabaud** [comment]
hi, I believe this is fixed at the same time as #102

**Comment by kmhallen** [comment]
Yes, the freezing issue is no longer present.

**Comment by vrabaud** [comment]
cool ! thx for testing. It's being released as we speak.
