### ISSUE TITLE
image_rotate crash during start

### ISSUE THREAD

**Issue by martimorta** [ros-perception/image_pipeline#103]
Hi
I am having the following error when image_rotate starts in Hydro with Ubuntu 12.04:
`image_rotate: /usr/include/boost/smart_ptr/shared_ptr.hpp:418: T* boost::shared_ptr<T>::operator->() const [with T = tf::TransformListener]: Assertion 'px != 0' failed.`

It is weird because I am using it in 5 identical cameras (PointGrey Ladybug2) and this only happens in 3 of them. 

Has somebody had the same problem or knows why is this happening?

Thanks in advance!

**Comment by vrabaud** [comment]
Is that bug repeatable ? Does it always happen with the same camera ? Does it work if you record the data in a rosbag and then replay it ? If so, please record and send me the bag !

**Comment by vrabaud** [comment]
a stack trace would also obviously help

**Comment by martimorta** [comment]
Hi Vincent,
I tried it about 5 times with the same result, same cameras failed.
Just a clarification it crashes when someone subscribes to the _rotated topic, for example using rqt_image_view or recording a bag.
I'll send more information as soon as possible (tomorrow probably).
Thanks for the quick answer btw!

**Comment by martimorta** [comment]
Hi,
I tried to repeat it again with different set ups and I don't know how everything works fine now, without having done any change. Weird.
ah well, I close the issue then. Thanks anyway!

**Comment by vrabaud** [comment]
well, it seems the transform listener was not being initialized, but the code is really basic there. Please get a stack trace next time, thx !
