### ISSUE TITLE
camera_calibration waiting for service camera/set_camera_info and crash

### ISSUE THREAD

**Issue by navdotnetreqs** [ros-perception/image_pipeline#1036]
Hi,

running ros-iron, ubuntu 22.04 and having installed all libraries via apt. I have a Logitech C920, and I run the camera with:
`ros2 run usb_cam usb_cam_node_exe --ros-args --remap /image_raw:=/camera/image_raw --remap /camera_info:=/camera/camera_info --params-file /home/user/.ros/camera_info/params_1.yaml`

I can confirm the image shows nicely in Rviz2 (adding an Image object), and ros2 topic hz /camera/image_raw gives

- average rate: 29.999
- 	min: 0.028s max: 0.043s std dev: 0.00251s window: 31

`ros2 topic echo /camera/camera_info sensor_msgs/CameraInfo`
gives plenty of data

```
header:
  stamp:
    sec: 1727666393
    nanosec: 486247000
  frame_id: camera
height: 480
width: 640
distortion_model: plumb_bob
d:
- -0.361976
```

Whatever I do I cannot seem to get the calibration running:

**ros2 run camera_calibration cameracalibrator --size 9x6 --square 0.023 --ros-args --remap image:=/camera/image_raw --remap camera:=/camera/camera_info**

> Waiting for service camera/set_camera_info ...
> Service camera/set_camera_info not found.
> Waiting for service left_camera/set_camera_info ...
> Service left_camera/set_camera_info not found.
> Waiting for service right_camera/set_camera_info ...
> Service right_camera/set_camera_info not found.
> Traceback (most recent call last):
>   File "/opt/ros/iron/lib/camera_calibration/cameracalibrator", line 33, in <module>
>     sys.exit(load_entry_point('camera-calibration==4.0.2', 'console_scripts', 'cameracalibrator')())
>   File "/opt/ros/iron/lib/python3.10/site-packages/camera_calibration/nodes/cameracalibrator.py", line 222, in main
>     node = OpenCVCalibrationNode("cameracalibrator", boards, options.service_check, sync,
>   File "/opt/ros/iron/lib/python3.10/site-packages/camera_calibration/camera_calibrator.py", line 255, in __init__
>     CalibrationNode.__init__(self, *args, **kwargs)
>   File "/opt/ros/iron/lib/python3.10/site-packages/camera_calibration/camera_calibrator.py", line 117, in __init__
>     raise RuntimeError("no camera service available")
> RuntimeError: no camera service available
> [ros2run]: Process exited with failure 1
> 

What is camera/set_camera_info and why is it not running..?

**Comment by mikeferguson** [comment]
The camera_info topic is different from the camera info service - the service is an optional ROS 2 service that allows setting the new parameters when the calibration is done. If your driver doesn't have a set_camera_info service, you can skip this by adding "--no-service-check" to your command (for more details, see https://docs.ros.org/en/rolling/p/camera_calibration/index.html)
