### ISSUE TITLE
How to use this package for monocular depth estimation

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [ros-perception/image_pipeline#1040]
Hello  Dear Community;

I have little knowledge of ROS. so I wanted to write here. I am trying to detect depth from the image coming from the monocular camera. Here, using this package, how can I convert it to point cloud data and use it for obstackle. 

Is it logical to use this package?

**Comment by mikeferguson** [comment]
Monocular depth estimation is not a current feature of this package (only creation of point clouds from depth images or depth + rgb).

**Comment by ahmet-f-gumustas** [comment]
Thank You
