### ISSUE TITLE
Fails calibration of the camera using ros indigo:

### ISSUE THREAD

**Issue by ajenjo85** [ros-perception/image_pipeline#110]
We have problems to try to calibrate a new camera using ros indigo.
The names or our topics are not default, because we have diferents cameras conneting in the same system.
We try to use the command cameracalibrator.py usign  --camera_name=/topic_name  --no-service-check but the system doesn't work.

The only way to end the calibration is remaping the topic when lauch the calibration:
rosrun camera_calibration cameracalibrator.py --size 9x6 --square 0.044 image:=/name_topic/image_color /camera/set_camera_info:=/name_topic/set_camera_info

**Comment by vrabaud** [comment]
what do you mean by does not work ?
what are the topics of your camera, image and set_Camera_info ?

**Comment by ajenjo85** [comment]
If you use a name of topic diferent that default, (/camera/set_camera) don't found the set_camera_info topic and need to do a remaping to finish the calibration proces.
 the system find the topic and finalice the calibration.
for example if we use:
rosrun camera_calibration cameracalibrator.py --size 9x6 --square 0.044 image:=camera2/rgb/image_color -> the system says that don't exist the topic  /camera/set_camera_info 

if Now use :
rosrun camera_calibration cameracalibrator.py --size 9x6 --square 0.044 image:=camera2/rgb/image_color   /camera/set_camera_info:=/camera2/rgb/set_camera_info-> the system works well remaping the set_camera_info topic to our case.

**Comment by vrabaud** [comment]
According to the fromt page of camera_calibration, you are supposed to do:

```
rosrun camera_calibration cameracalibrator.py --size 9x6 --square 0.044 image:=/name_topic/image_color camera:=/name_topic
```

Does that work for you ?

**Comment by Saikat2019** [comment]
this is very good tutorial...helped me a lot in my project youtube link - [https://www.youtube.com/watch?v=WvGcxJ1L3NM](url) ...you may refer to this tutorial...hope it will help

**Comment by JWhitleyWork** [comment]
Closed due to resolution.
