### ISSUE TITLE
image_rotate fails to load library libimage_rotate.so in Groovy

### ISSUE THREAD

**Issue by fiannaca** [ros-perception/image_pipeline#111]
When trying to run the example code on the image_rotate page in the ROS wiki, I get the following error. I tested this on three separate computers all running Groovy (working with a PR2):

```
rosrun image_rotate image_rotate image:=l_forearm_cam/image_color rotated/image:=l_forearm_cam/image_color_rotated __name:=image_rotater

[ERROR] [1415309064.421543229]: Failed to load nodelet [/image_rotater] of type [image_rotate/image_rotate]: Failed to load library /opt/ros/groovy/lib//libimage_rotate.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /opt/ros/groovy/lib//libimage_rotate.so: undefined symbol: _ZTVN3tf212BufferClientE)
```

I think it is caused by a run_depends issue, but I'm not sure.

**Comment by trainman419** [comment]
This looks like the image_rotate library isn't linked against tf2 properly.

Since Groovy is EOL, it is no longer possible to do a release to correct this issue.

**Comment by fiannaca** [comment]
If I were to download the code and patch it locally, what would I have to do to correctly setup the cmake file to make it link properly against tf2?

**Comment by trainman419** [comment]
It might be as simple as adding tf2_ros to the `find_package(catkin ... )` line, since there already appears to be a build_depend and a run_depend on tf2_ros.

**Comment by vrabaud** [comment]
sorry, not supported anymore.
