### ISSUE TITLE
camera_calibration not working at compressed format

### ISSUE THREAD

**Issue by LEE-JAE-SEONG** [ros-perception/image_pipeline#118]
camera_calibration not working at compressed format
I use Indigo, Ubuntu 14.04, 
calibration only working at raw ?

**Comment by vrabaud** [comment]
yes indeed. Is it because you are not using ImageTransport ? (which would have a raw topic) or because you are over wifi ?

**Comment by LEE-JAE-SEONG** [comment]
Thank you, vrabaud 
After typing the command ImageTransport,
able to transport compressed data to raw data

**Comment by vrabaud** [comment]
cool, so closing this one.
