### ISSUE TITLE
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections

### ISSUE THREAD

**Issue by alexus37** [ros-perception/image_pipeline#125]
Hi,
I have a problem using image_view on my system (Trusty, indigo). 
When I try to get a image by running

rosrun image_view image_view image:=/IR_data

everytime a new frame arives I get this error:

QMetaMethod::invoke: Unable to invoke methods with return values in queued connections

Do you have any idea want could cause this?!

Thanks for your help.

Btw I have opencv 2.4.9 installed

**Comment by vrabaud** [comment]
did you compile OpenCV yourself ? Which OS ?

**Comment by alexus37** [comment]
Yes I compiled opencv myself following this guide 

http://www.samontab.com/web/2014/06/installing-opencv-2-4-9-in-ubuntu-14-04-lts/

My OS is Ubuntu 14.04

**Comment by alexus37** [comment]
hi,
I found a solution, I just recompiled opencv 2.4.9 without QT!
That fix it for me!
