### ISSUE TITLE
Is that possible to view BGRA/RGBA image with image_view?

### ISSUE THREAD

**Issue by wkentaro** [ros-perception/image_pipeline#127]
I'd like to view image which encoding is BGRA or RGBA with image_view.
Is that possible? Or do I need to change some codes?

**Comment by vrabaud** [comment]
that would be a question for http://answers.ros.org/questions/ . But it does yes. Does it not work for you ?

**Comment by wkentaro** [comment]
> that would be a question for http://answers.ros.org/questions/ .

Sorry about that. I thought this will be a feature request or a bug report.

It can be viewed but the transparent pixels does not viewed as transparent.

Left is image_view, Right is png image viewed with Image Viewer on Ubuntu.
![image](https://cloud.githubusercontent.com/assets/4310419/7558303/4f1bee8c-f7dc-11e4-9e3c-b357ad27472f.png)

**Comment by vrabaud** [comment]
ok, so your question if more of a bug report :)
The transparent pixels are actually converted to black (that is the OpenCV convention). What would you expect ?

**Comment by wkentaro** [comment]
I see. This may be confusing but I'd expect the transparent pixels are
converted to the same color as image_view's bg (I don't know the color code
but it's gray.)

**Comment by wkentaro** [comment]
I'm closing this since I don't need this feature anymore. (actually, I forgot why I needed this..)
Thanks for the comment!
