### ISSUE TITLE
Cameracalibrate.py truncates calibration data

### ISSUE THREAD

**Issue by chrisspen** [ros-perception/image_pipeline#129]
I completed the calibration tutorial for a stereo camera using two USB cameras. There's no documentation about what to do with the calibration data generated, but from various posts on answers.ros.org, it seems you're supposed to do something with an undocumented YAML file generated by clicking the "Commit" button. I eventually discovered this file in ~/.ros/camera_info/head_camera.yaml.

However, this file only contains calibration data for one of the two cameras. Comparing it to the ost.txt file generated in the /tmp/calibrationdata.tar.gz shows it's missing half the calibration data needed to use a stereo camera. Is this an error?

**Comment by JWhitleyWork** [comment]
Closing old thread due to no longer being applicable to currently-supported ROS version.
