### ISSUE TITLE
After commit the calibration data to camera all driver segment fault

### ISSUE THREAD

**Issue by StanleyYake** [ros-perception/image_pipeline#135]
Hello there:
    when I calibration the camera and push the button commit(really regret), then I convert the ost.txt to camera.yaml and put it in the ./ros/camera_info directory and `rosrun uvc_cam uvc_cam_node` throw Segment Fault.And when I remove the camera.yaml it throw the same error.also I have tried some other drivers ,nothing good happen, but when I use another computer, and didn't calibrate, it could open the camera.I wonder if there is another config file in my computer and all the driver will load in advance, but the config is wrong or not so good ,so all driver can't open the camera.By the way, I could use the app cheese to open it ,but the color is a little strange.
![screenshot from 2015-06-09 15 38 11](https://cloud.githubusercontent.com/assets/7522853/8052896/4bdd319c-0ebe-11e5-85eb-ce6a61755eb1.png)
![screenshot from 2015-06-09 15 38 34](https://cloud.githubusercontent.com/assets/7522853/8052899/532d8082-0ebe-11e5-8e0f-41e07abad590.png)
![screenshot from 2015-06-09 16 21 31](https://cloud.githubusercontent.com/assets/7522853/8053640/26765756-0ec5-11e5-894c-e4f0d529fc27.png)

**Comment by StanleyYake** [comment]
![Uploading Screenshot from 2015-06-09 16:21:31.png…]()

**Comment by vrabaud** [comment]
do you have the obtained calibration file ? Do you have the default one from uvc_cam ?

**Comment by StanleyYake** [comment]
Hi vrabaud:
    Thanks for your answer. After calibration, I get a compressed file, and there is a file named ost.txt in it which is the calibration file.But I didn't have the default one , I thought it should be in the camera firmware.
    BTW, I found another package `libuvc_camera` http://wiki.ros.org/libuvc_camera which is the only one work on my computer

**Comment by JWhitleyWork** [comment]
Closed due to resolution.
