### ISSUE TITLE
rewrite image_view with ecto

### ISSUE THREAD

**Issue by vrabaud** [ros-perception/image_pipeline#14]
At least, we should see the overlap with rqt

**Comment by macmason** [comment]
I'd like to register my support for having a as-lightweight-as-possible thing for viewing image topics (where lightweight means "doesn't require starting up rviz"; I don't care if it needs QT). 

I don't know if that's what this issue is or not, so I thought I'd chime in.

**Comment by vrabaud** [comment]
ok, so we can keep it then :) rqt is much lighter weight than RViz but it's still a GUI.
image_view has synchronization issues (nodelets duuh) that arehacked around  right now (GTK stuff that actually causes issues on Mac).
The right solution is then to ecto-ify it (knowing that all the cells are already there ....). I just need time :)

**Comment by macmason** [comment]
Raw image_view has synchronization issues? I thought it just did one topic at a time.

I must be remembering this all wrong, because I thought it just did listen -> cv_bridge -> highgui, and therefore worked everywhere that OpenCV does (albeit with a slightly inconsistent gui).

**Comment by vrabaud** [comment]
yop, it does exactly so. Through nodelets ....
And with the crazy nodelet threading even though some windows are closed in OpenCV, you need to do more to really kill the process.

**Comment by macmason** [comment]
Weird. 

How about we leave the ticket open as "make image_view less broken"?

**Comment by vrabaud** [comment]
No need for ecto, just without nodelets with #166.
