### ISSUE TITLE
Calibrate cameras with different resolution

### ISSUE THREAD

**Issue by rocklinsuv** [ros-perception/image_pipeline#141]
Hi All,

I'm wondering if I could use the stereo calibration feature in this package to obtain the fundamental/essential matrix of two cameras in different resolutions and focal lenses? Or the cameras has to be exactly the same? Please correct me if I'm wrong. Many thanks!

Cheers,
Lyn

**Comment by IN-Gamut** [comment]
well you can't do that with this package. I am trying to do that also.
