### ISSUE TITLE
stereo_view and extract_images gives segmentation fault

### ISSUE THREAD

**Issue by dakshshukla** [ros-perception/image_pipeline#142]
I am using ROS Jade, on my desktop, with Ubuntu 14.04 OS. I have connected 2 mvBlueFOX-MLC-202bG cameras via USB and am using the bluefox2 driver (https://github.com/KumarRobotics/bluefox2) to operate them and take stereo images. The driver runs fine, I can also see the 2 images with these 2 cameras in separate windows, using rqt_image_view. now, I want to save these stereo images to a directory, so I used rosbag command to save images from one of the topics. I have a rosbag file containing image messages, with the following description:
rosbag info left.bag 
path:        left.bag
version:     2.0
duration:    35.7s
start:       Jun 30 2015 17:40:57.81 (1435704057.81)
end:         Jun 30 2015 17:41:33.49 (1435704093.49)
size:        515.8 MB
messages:    440
compression: none [440/440 chunks]
types:       sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]
topics:      /stereo/left/image_raw   440 msgs    : sensor_msgs/Image

when I am extracting these images, this is giving me the following error:

rosrun image_view extract_images _sec_per_frame:=0.01 image:=/stereo/left/image_raw
Segmentation fault (core dumped)

Also, when I am trying to view the stereo images from my 2 camera nodes:

rosrun image_view stereo_view stereo:=/stereo image:=image_raw
Segmentation fault (core dumped)

This makes me believe that there is some problem with the image_pipeline package. I have installed it using:

sudo apt-get install ros-jade-image-pipeline

And, I have also tried to git clone it in my catkin_ws workspace, inside the src directory, and have done catkin_make, which gives the following output and some errors:
Base path: /home/dakshshukla/catkin_ws
Source space: /home/dakshshukla/catkin_ws/src
Build space: /home/dakshshukla/catkin_ws/build
Devel space: /home/dakshshukla/catkin_ws/devel
Install space: /home/dakshshukla/catkin_ws/install
#### 
#### 
#### 
#### 

[  1%] [  3%] [  5%] Built target disparity_view
[  7%] Built target image_saver
[  9%] Built target bluefox2_gencfg
[ 11%] Built target image_view_exe
Built target extract_images
Built target video_recorder
[ 13%] Building CXX object image_pipeline/image_view/CMakeFiles/image_view.dir/src/nodelets/image_nodelet.cpp.o
[ 13%] [ 15%] Built target stereo_view
Built target std_msgs_generate_messages_lisp
[ 15%] [ 15%] Built target std_msgs_generate_messages_py
Built target std_msgs_generate_messages_eus
[ 15%] Built target std_msgs_generate_messages_cpp
[ 15%] [ 15%] Built target nodelet_generate_messages_lisp
[ 15%] [ 15%] Built target roscpp_generate_messages_eus
Built target nodelet_generate_messages_cpp
Built target bond_generate_messages_eus
[ 15%] Built target bond_generate_messages_cpp
[ 15%] [ 15%] Built target _bluefox2_generate_messages_check_deps_SetExposeSrv
Built target sensor_msgs_generate_messages_cpp
[ 15%] [ 15%] Built target nodelet_generate_messages_eus
Built target geometry_msgs_generate_messages_eus
[ 15%] [ 15%] [ 15%] [ 15%] [ 15%] Built target geometry_msgs_generate_messages_cpp
Built target sensor_msgs_generate_messages_lisp
Built target sensor_msgs_generate_messages_py
Built target geometry_msgs_generate_messages_lisp
Built target sensor_msgs_generate_messages_eus
[ 15%] [ 15%] [ 15%] [ 15%] [ 15%] Built target geometry_msgs_generate_messages_py
Built target roscpp_generate_messages_py
[ 15%] Built target roscpp_generate_messages_cpp
Built target rosgraph_msgs_generate_messages_eus
Built target nodelet_generate_messages_py
Built target rosgraph_msgs_generate_messages_cpp
[ 15%] Built target rosgraph_msgs_generate_messages_py
[ 15%] Built target bond_generate_messages_lisp
[ 15%] Built target roscpp_generate_messages_lisp
[ 15%] [ 15%] [ 15%] [ 15%] Built target rosgraph_msgs_generate_messages_lisp
Built target bond_generate_messages_py
Built target dynamic_reconfigure_generate_messages_cpp
Built target dynamic_reconfigure_generate_messages_lisp
[ 15%] Built target diagnostic_msgs_generate_messages_cpp
[ 15%] [ 15%] Built target dynamic_reconfigure_generate_messages_py
[ 15%] Built target dynamic_reconfigure_generate_messages_eus
Built target diagnostic_msgs_generate_messages_lisp
[ 15%] [ 15%] [ 15%] Built target diagnostic_msgs_generate_messages_eus
Built target diagnostic_msgs_generate_messages_py
Built target dynamic_reconfigure_gencfg
[ 21%] [ 23%] Built target image_proc_gencfg
[ 25%] Built target stereo_image_proc_gencfg
Built target image_rotate_gencfg
[ 26%] [ 28%] Built target image_rotate_exe
Built target bluefox2_generate_messages_lisp
[ 32%] [ 48%] Built target bluefox2_generate_messages_py
Built target depth_image_proc
[ 50%] Built target bluefox2_generate_messages_cpp
[ 53%] Built target bluefox2_generate_messages_eus
[ 65%] Built target image_proc
[ 65%] Built target bluefox2_gencpp
[ 67%] [ 67%] Built target image_rotate
Built target bluefox2_generate_messages
[ 73%] [ 75%] Built target stereo_image_proc
Built target image_proc_exe
[ 88%] Built target bluefox2
[ 90%] Built target stereoimageproc_exe
[ 92%] Built target list_cameras
[ 94%] Built target single_node
[ 96%] Built target stereo_node
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /home/dakshshukla/catkin_ws/src/image_pipeline/image_view/src/nodelets/image_nodelet.cpp:46:
/home/dakshshukla/catkin_ws/src/image_pipeline/image_view/src/nodelets/image_nodelet.cpp: In member function ‘virtual void image_view::ImageNodelet::onInit()’:
/home/dakshshukla/catkin_ws/src/image_pipeline/image_view/src/nodelets/image_nodelet.cpp:145:73: error: ‘cvGetWindowHandle’ was not declared in this scope
   GtkWidget *widget = GTK_WIDGET( cvGetWindowHandle(window_name_.c_str()) );
                                                                         ^
make[2]: **\* [image_pipeline/image_view/CMakeFiles/image_view.dir/src/nodelets/image_nodelet.cpp.o] Error 1
make[1]: **\* [image_pipeline/image_view/CMakeFiles/image_view.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j8 -l8" failed

Could anyone please help me out with this issue?

**Comment by vrabaud** [comment]
Do you have a custom OpenCV ? (not an Ubuntu package). That's the only reason why the compilation would fail.
