### ISSUE TITLE
support fisheye calibration using opencv 3.0

### ISSUE THREAD

**Issue by protobits** [ros-perception/image_pipeline#146]
OpenCV 3.0 now has support for fisheye lens calibration and related distortion/projection functions.
This could be used to extend ROS's support towards calibrating and processing images acquired with fisheye lenses.

http://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#fisheye

I guess one possibility is to add another distortion model keyword, which would indicate these additional functions need to be used. I believe only a skew coefficient is needed as a separate parameter for calibration.

**Comment by DavidTorresOcana** [comment]
Hello
Perhaps too late, but I added this functionality in this fork: [image_pipeline](https://github.com/DavidTorresOcana/image_pipeline)

You can calibrate (with a tool) and rectify fisheye cameras.

The results for high FOV (+180deg) are better that those achieved with the current implementation

**Comment by DaikiMaekawa** [comment]
@DavidTorresOcana Thanks for sharing. I think fisheye is one of the things that has to be supported by image_pipeline. So, it would be nice to include your changes into the upstream repo. What's stands in the way of creating a PR?

**Comment by Roemer** [comment]
Any news here? That feature could be really handy.

**Comment by SteveMacenski** [comment]
@roemer PRs welcome. #440 and #441 do the bulk of the work but need someone to help get over the line. 

I dont have a fisheye camera or use for one so I need someone with some need for it to respond to comments
