### ISSUE TITLE
image_view: Attempt to unlock mutex that was not locked

### ISSUE THREAD

**Issue by joseparnau** [ros-perception/image_pipeline#153]
Hi,

I tried to visualize an image captured from the parrot ardrone 2 using the image_view node and i got:

---

$ rosrun image_view image_view image:=/ardrone/front/image_raw
[ INFO] [1445004668.853536140]: Using transport "raw"
[ INFO] [1445004669.204656248]: Press 'q' on the window to stop the node
Attempt to unlock mutex that was not locked
Aborted

---

There was this issue (https://github.com/ros-perception/image_pipeline/issues/106) in October 2014 but seems it was fixed.

Any clue?

My ROS version is Jade on Debian.

Thank's in advance.

**Comment by joseparnau** [comment]
It works with Ubuntu Jade so it seems that Debian might be the problem...

**Comment by joseparnau** [comment]
Hi,
It looks like the error might be due to my own installation. You can close the thread.

**Comment by vrabaud** [comment]
if you ever figure out, please let me know. Thx
