### ISSUE TITLE
Missing pthread library at link time

### ISSUE THREAD

**Issue by cottsay** [ros-perception/image_pipeline#16]
image_rotate does not compile on Fedora because pthread is not linked in. I think that the root of this problem is in OpenCV (which is where the pthread routines are used) but it doesn't seem to have affected any packages but this one.

Adding "pthread" to the link_libraries will allow image_rotate to compile on Fedora, but I don't know if this is the BEST solution.

**Comment by vrabaud** [comment]
thx. Can you please let us know which error you get exactly (make output)

**Comment by cottsay** [comment]
Of course, here is the output:

<pre>
==> Processing catkin package: 'image_rotate'
==> Creating build directory: 'build_isolated/image_rotate'
==> Building with env: '/home/cottsay/ros_catkin_ws/devel_isolated/image_proc/env.sh'
==> cmake /home/cottsay/ros_catkin_ws/src/image_rotate -DCATKIN_DEVEL_PREFIX=/home/cottsay/ros_catkin_ws/devel_isolated/image_rotate -DCMAKE_INSTALL_PREFIX=/home/cottsay/ros_catkin_ws/install_isolated -DSETUPTOOLS_DEB_LAYOUT=OFF
==> make -j4 -l4 in '/home/cottsay/ros_catkin_ws/build_isolated/image_rotate'
Scanning dependencies of target image_rotate_gencfg
[ 50%] Built target image_rotate_gencfg
Scanning dependencies of target image_rotate
[100%] Building CXX object CMakeFiles/image_rotate.dir/src/node/image_rotate.cpp.o
Linking CXX executable /home/cottsay/ros_catkin_ws/devel_isolated/image_rotate/lib/image_rotate/image_rotate
/usr/bin/ld: CMakeFiles/image_rotate.dir/src/node/image_rotate.cpp.o: undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
/usr/bin/ld: note: 'pthread_mutexattr_settype@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line
/lib64/libpthread.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [/home/cottsay/ros_catkin_ws/devel_isolated/image_rotate/lib/image_rotate/image_rotate] Error 1
make[1]: *** [CMakeFiles/image_rotate.dir/all] Error 2
make: *** [all] Error 2
<== Failed to process package 'image_rotate': 
  Command '/home/cottsay/ros_catkin_ws/devel_isolated/image_proc/env.sh make -j4 -l4' returned non-zero exit status 2
Reproduce this error by running:
==> /home/cottsay/ros_catkin_ws/devel_isolated/image_proc/env.sh make -j4 -l4
Command failed, exiting.
</pre>

**Comment by vrabaud** [comment]
ok thx, I wanted to know better where the error was from. It cannot be from OpenCV as no GUI from OpenCV is used in that code.
The pthread it is using is most likely from roscpp which was not find_packaged. I just pushed that to trunk, can you please confirm that this works ? thx.

**Comment by cottsay** [comment]
No dice, same error. Could it be Boost-related?

**Comment by vrabaud** [comment]
ok, I fear the error is deeper. Can you please add this to your CMakeLists.txt im image_rotate:

message(INFO " *************\* catkin LIBRARIES: " ${catkin_LIBRARIES})
message(INFO " *************\* roscpp LIBRARIES: " ${roscpp_LIBRARIES})

right after

find_package(catkin REQUIRED COMPONENTS cv_bridge dynamic_reconfigure image_transport roscpp tf)

Thx. (pthread should be in roscpp_LIBRARIES and hence in catkin_LIBRARIES)

**Comment by cottsay** [comment]
As requested:

pthread is NOT present. Is this a problem in catkin? roscpp?

INFO *************\* catkin LIBRARIES: /home/cottsay/ros_catkin_ws/install_isolated/lib/libcv_bridge.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_calib3d.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_contrib.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_core.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_features2d.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_flann.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_gpu.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_highgui.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_imgproc.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_legacy.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_ml.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_nonfree.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_objdetect.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_photo.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_stitching.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_ts.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_video.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libopencv_videostab.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librosconsole.so/usr/lib64/libboost_regex-mt.so/usr/lib64/libboost_thread-mt.so/usr/lib64/liblog4cxx.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp_serialization.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libdynamic_reconfigure_config_init_mutex.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libimage_transport.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libmessage_filters.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp.so/usr/lib64/libboost_signals-mt.so/usr/lib64/libboost_filesystem-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libxmlrpcpp.so/usr/lib64/libtinyxml.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libclass_loader.so/usr/lib64/libdl.so/usr/lib64/libPocoFoundation.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libconsole_bridge.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroslib.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libtf.so
INFO *************\* roscpp LIBRARIES: /home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp.so/usr/lib64/libboost_signals-mt.so/usr/lib64/libboost_filesystem-mt.so/usr/lib64/libboost_system-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp_serialization.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librosconsole.so/usr/lib64/libboost_regex-mt.so/usr/lib64/libboost_thread-mt.so/usr/lib64/liblog4cxx.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp_serialization.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp_serialization.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp_serialization.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libroscpp_serialization.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/librostime.so/usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libxmlrpcpp.so/home/cottsay/ros_catkin_ws/install_isolated/lib/libcpp_common.so

**Comment by vrabaud** [comment]
ok, so we definitely get pthread on Ubuntu and that comes from Boost.
Sorry to ask you again but I don't have a Fedora iso here. Can you plaese do the following and give us the output in any of your CMake ? thx

find_package(Boost REQUIRED COMPONENTS date_time system thread)
message(INFO "${Boost_LIBRARIES}")

it seems your Boost_LIBRARIES does not have pthread. I am really surprised this package is the first one you hit with that issue. Which version of boost do you have ? Also, what is that *-mt version you have ? Thx.

**Comment by cottsay** [comment]
The output:

<pre>
INFO **************  Boost LIBRARIES: /usr/lib64/libboost_date_time-mt.so/usr/lib64/libboost_system-mt.so/usr/lib64/libboost_thread-mt.so
</pre>

As of now, this is the only package in desktop-full (wet or dry) that has this issue on Fedora.

Boost on Fedora 18 is 1.50.0 (which caused issues in our F18 Electric builds, too). All of the libboost*-mt.so are 1.50.0

I'm happy to continue testing things as you have ideas. Thanks much for your time and help on this!

**Comment by vrabaud** [comment]
Well, congrats, you found a core issue :) I filed a bug report:
https://github.com/ros/ros_comm/issues/135

I will not fix it for image_pipeline but will wait for upstream fixes.

**Comment by cottsay** [comment]
Thanks much, I'll keep an eye on it and we'll just link manually as a workaround until an upstream fix is pushed.

**Comment by vrabaud** [comment]
yes, for now, just follow the instructions at:
http://stackoverflow.com/questions/1620918/cmake-and-libpthread

**Comment by vrabaud** [comment]
ok, that got fixed in https://github.com/ros/ros_comm/issues/135
