### ISSUE TITLE
compilation error: 'cvtColorForDisplay' is not member of 'cv_bridge'

### ISSUE THREAD

**Issue by MuhammadUsman90** [ros-perception/image_pipeline#167]
I am trying to compile Image_view Pipeline in Ros. When i do catkin_make it gave me this error. I am using odroid board XU4. Opencv has been compiled from source and it give no errors
![img_5532mod](https://cloud.githubusercontent.com/assets/7099741/11811870/757086da-a338-11e5-8d5f-93df0ac950e5.jpg)

**Comment by vrabaud** [comment]
You need to have at least version 1.11.9 of cv_bridge: https://github.com/ros-perception/vision_opencv/blob/indigo/cv_bridge/CHANGELOG.rst
The package.xml should indeed add a minimum requirement on cv_bridge.

**Comment by vrabaud** [comment]
fixed in 016c276569f93352a356c0fefc8c9b0cf420f7a6
