### ISSUE TITLE
camera_calibration coredumps when calibrating against 1920x1440 size image

### ISSUE THREAD

**Issue by sameerparekh** [ros-perception/image_pipeline#19]
After calibrating using a 1920x1440 source video stream, during the save process, camera_calibration coredumps: 

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by vrabaud** [comment]
Hi, that error is very generic. Can you maybe:
- provide a back trace
- gdb it to figure out in which function that is happening under which conditions.
  Thx

**Comment by chadrockey** [comment]
The system isn't running of out memory/swap is it?  That's a moderately large video stream, so if it requires many samples, it could eat a significant chunk of memory.

**Comment by sameerparekh** [comment]
Yeah it might be out of memory/swap. Will try again with more memory configured for my VM. Thanks.

**Comment by vrabaud** [comment]
any news on that one ?

**Comment by vrabaud** [comment]
closing for now: no proof that it's from the code
