### ISSUE TITLE
cannot load depth_image_proc::ConvertMetricNodelet

### ISSUE THREAD

**Issue by jihoonl** [ros-perception/image_pipeline#2]
I confirmed that nodelet manager cannot load depth_image_proc::convertMetricNodelet.

I tried in this way.

terminal1:

> rosrun nodelet nodelet manager __name:=nodelet_manager 

terminal2:

>  rosrun nodelet nodelet load depth_image_proc/convert_metric nodelet_manager

The below log is from nodelet_manager

Debug:   class_loader::class_loader_core: Attempting to load library /home/jihoonl/ros_groovy/image_pipeline/depth_image_proc/build/devel/lib//libdepth_image_proc.so...

[ERROR] [1353032108.854135923]: Failed to load nodelet [/depth_image_proc_convert_metric] of type [depth_image_proc/convert_metric]: Failed to load library /home/jihoonl/ros_groovy/image_pipeline/depth_image_proc/build/devel/lib//libdepth_image_proc.so. Make sure that you are calling the PLUGINLIB_REGISTER_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = Cannot load library)
Debug:   class_loader::class_loader_core: Attempting to load library /home/jihoonl/ros_groovy/image_pipeline/depth_image_proc/build/devel/lib//libdepth_image_proc.so...

Debug:   class_loader::MultiLibraryClassLoader: Attempting to create instance of class type depth_image_proc::ConvertMetricNodelet.
[ERROR] [1353032141.539973295]: Failed to load nodelet [/depth_image_proc_convert_metric] of type [depth_image_proc/convert_metric]: MultiLibraryClassLoader: Could not create object of class type depth_image_proc::ConvertMetricNodelet as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()

**Comment by vrabaud** [comment]
are you on Fuerte/Groovy ?
Which version are you using ? src/deb ? which version of the deb/OS. Thx

**Comment by jihoonl** [comment]
This is groovy. and I tested both deb and src.

OS precise 12.04
Package: ros-groovy-depth-image-proc
Status: install ok installed
Priority: extra
Section: misc
Installed-Size: 939
Maintainer: Vincent Rabaud vrabaud@willowgarage.com
Architecture: amd64
Version: 1.9.9-0precise-20121111-1733-+0000
Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.2.1), ros-groovy-nodelet, libboost-all-dev, ros-groovy-cv-bridge, ros-groovy-pcl-ros
Description: Contains nodelets for processing depth images such as those produced by OpenNI camera. Functions include creating disparity images and point clouds, as well as registering (reprojecting) a depth image into another camera frame.
Homepage: http://ros.org/wiki/depth_image_proc

**Comment by vrabaud** [comment]
this is a pluginlib issue and I think it has been fixed. Can you please upgrade to the latest packages from today ? Thx
After that, I did get another bug but I fixed it in image_pipeline 1.9.10. Please confirm that it works for you, thx.

**Comment by jihoonl** [comment]
I got it working!! yay! Thanks Vincent!
