### ISSUE TITLE
stereo_image_proc headers not installed?

### ISSUE THREAD

**Issue by ideasrule** [ros-perception/image_pipeline#20]
On Groovy, I get this error when compiling a project, using catkin_make, that uses stereo_image_proc: stereo_image_proc/processor.h: No such file or directory

I went to /opt/ros/groovy/include/stereo_image_proc, and indeed, it only contains one file: DisparityConfig.h. Why is this the case? Where did the other header files go?  I asked this question on ROS Answers:
http://answers.ros.org/question/58316/stereo_image_procprocessorh-no-such-file-or-directory/

and a user told me to report it here because it looks like a bug.  I'm running Ubuntu 12.04, and installed ROS with apt-get install ros-groovy-desktop-full.

**Comment by vrabaud** [comment]
yop, that was indeed a bug, thx ! 1.10.6 is being released now.
