### ISSUE TITLE
[imgwarp.cpp] crashes: OpenCV Error: Assertion failed (_map1.size().area() > 0) in remap

### ISSUE THREAD

**Issue by willdzeng** [ros-perception/image_pipeline#209]
I have a node that publishing following topic under namespace "camera"

```
/left/image_raw
/left/camera_info
/right/image_raw
/right/camera_info
```

and I am trying to use **stereo_image_proc** node to rectify the image.

`<node pkg="stereo_image_proc" type="stereo_image_proc" name="stereo_image_proc" respawn="true" output="screen" ns="camera"/>`

but the node crashes when I subscribe the image_rect from rviz.

> OpenCV Error: Assertion failed (_map1.size().area() > 0) in remap, file /home/zeng/essential/opencv/modules/imgproc/src/imgwarp.cpp, line 4833
> terminate called after throwing an instance of 'cv::Exception'
>   what():  /home/zeng/essential/opencv/modules/imgproc/src/imgwarp.cpp:4833: error: (-215) _map1.size().area() > 0 in function remap

I am using ROS Indigo, Ubuntu 14.04, OpenCV3.1
cv_bridge is 1.12.0 indigo branch build from source.
Image_pipeline is up-to-date indigo branch, also tried 1.12.16 release, same issue.

**Comment by willdzeng** [comment]
Fixed by re-calibrate camera. The old calibration is bad.

Maybe put a Print about this when the assertion failed?

**Comment by TZVIh** [comment]
Hi,
I have the same problem, I am using https://github.com/willdzeng/zed_cpu_ros
what should I do?
Thanks!

**Comment by willdzeng** [comment]
As I mentioned previously, recalibrate would fix this problem, I suggest you directly use the opencv calibration package instead of using the build-in ZED calibration
