### ISSUE TITLE
Unable to cleanly exit image_view

### ISSUE THREAD

**Issue by chrisspen** [ros-perception/image_pipeline#221]
Is there some sort of trick for closing image_view? Clicking the standard "x" close button in the window titlebar does nothing. Sending it ctrl+c in the console does nothing. The window doesn't seem to respond to any standard exit keys like Esc or Q. I find I almost always have to use `kill` to close it.

**Comment by chaonan99** [comment]
I have the same problem. I have to restrain my impulse on clicking "X" and only use ctrl+c to quit. Otherwise (if click "X" first) nothing but killing the window would work.

**Comment by JWhitleyWork** [comment]
Should be closed by #481 in ROS1 and #475 in ROS2.
