### ISSUE TITLE
camera calibrator starts very small

### ISSUE THREAD

**Issue by ahendrix** [ros-perception/image_pipeline#23]
The initial window size for the camera calibrator is quite small. This makes it difficult to see, which makes me sad.

**Comment by vrabaud** [comment]
you can resize it can you ? or not ?

**Comment by trainman419** [comment]
Yep; it resizes just fine.

I think this bug was introduced when the output image of the camera calibration was downsampled from 640x480 to 320x240, because the window just shows up with the same size as the camera image.

**Comment by JWhitleyWork** [comment]
Closing due to resolution.
