### ISSUE TITLE
could not convert ‘use_dynamic_range’ from ‘bool’ to ‘cv_bridge::CvtColorForDisplayOptions’

### ISSUE THREAD

**Issue by fabrizioschiano** [ros-perception/image_pipeline#230]
Hi everyone, 

It is not really an issue because I solved already my problem. But I wanted to post it here anyway because it could help someone in the future.

I was at an earlier version of the package and I had the following error while compiling the package: 

```
[  6%] /catkin_ws/src/image_pipeline/image_view/src/nodes/video_recorder.cpp: In function ‘void callback(const ImageConstPtr&, const CameraInfoConstPtr&)’:
/catkin_ws/src/image_pipeline/image_view/src/nodes/video_recorder.cpp:75:153: error: could not convert ‘use_dynamic_range’ from ‘bool’ to ‘cv_bridge::CvtColorForDisplayOptions’
       const cv::Mat image = cv_bridge::cvtColorForDisplay(cv_bridge::toCvShare(image_msg), encoding, use_dynamic_range, min_depth_range, max_depth_range)->image;
```

Then I did a git pull and it solved my problem. 

I hope this can help someone who will encounter the same problem.

**Comment by vrabaud** [comment]
That got fixed in https://github.com/ros-perception/image_pipeline/commit/ecc99325c433f3adf02541dbd7525ae6de3c5a28#diff-deffa49f7e8be4cc40839aeeee73cda1
