### ISSUE TITLE
How to validate the intrinsic calibration

### ISSUE THREAD

**Issue by zfxw0206** [ros-perception/image_pipeline#232]
Now I am using this package to calibrate my camera, but I found that every time I calibrated the camera, I got different values for f_x, f_y, c_x, c_y. How can I know which is right and which is incorrect.
 There is a "test" folder in this package, can I use this code to test these values? If so, how can I run it?

**Comment by vrabaud** [comment]
Please ask questions on http://answers.ros.org/questions/
And have a look at the documentation:
http://wiki.ros.org/camera_calibration?distro=kinetic#cameracheck.py 
http://wiki.ros.org/camera_calibration?distro=kinetic#Camera_Check
http://wiki.ros.org/image_proc?distro=kinetic
