### ISSUE TITLE
Stereo image registration using GPU

### ISSUE THREAD

**Issue by furushchev** [ros-perception/image_pipeline#234]
Since OpenCV 3 supports stereo image registration using GPU device, I'd like to let `stereo_image_proc` use GPU for further performance.
When providing via `apt` package, it needs runtime condition that check if CUDA is enabled and switch the methods.
Is there any ideas to achieve this feature?

**Comment by vrabaud** [comment]
Duplicate of https://github.com/ros-gbp/opencv3-release/issues/5
You would need your own OpenCV I believe.
