### ISSUE TITLE
Document the flags for cameracalibrator

### ISSUE THREAD

**Issue by ahendrix** [ros-perception/image_pipeline#24]
From reading the source for cameracalibrator.py, it has a lot of flags that aren't documented on the wiki.

The popular/supported flags for cameracalibrator should be documented on the wiki. This probably includes the --pattern, --size and --square flags.

It may be sufficient to copy the output of cameracalibrator.py --help onto the wiki.

**Comment by vrabaud** [comment]
Done. It seems there are deprecated flags, I'll look into them.
