### ISSUE TITLE
image_proc failing to build on Arch

### ISSUE THREAD

**Issue by alphayed** [ros-perception/image_pipeline#243]
``` bash
[ 23%] Built target image_proc_gencfg
[ 84%] Built target image_proc
[ 92%] Linking CXX executable /home/alphayed/ROS/ros_catkin_ws/devel_isolated/image_proc/lib/image_proc/image_proc
/home/alphayed/ROS/ros_catkin_ws/install_isolated/lib/libopencv_viz3.so.3.1.0: undefined reference to `vtkSTLReader::New()'
/home/alphayed/ROS/ros_catkin_ws/install_isolated/lib/libopencv_viz3.so.3.1.0: undefined reference to `vtkOBJReader::New()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/image_proc_exe.dir/build.make:219: /home/alphayed/ROS/ros_catkin_ws/devel_isolated/image_proc/lib/image_proc/image_proc] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/image_proc_exe.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```
I've compiled opencv3 from source but that didn't help. Can you please guide me on this issue?

**Comment by vrabaud** [comment]
Did you compile your OpenCV3 or did you use the official ROS ones?

**Comment by alphayed** [comment]
I installed the officially supported one using Arch's package manager. When image_proc failed while compiling ROS packages I removed it and used the one that is a part of ROS packages. Image_proc fails to compile either way.

**Comment by vrabaud** [comment]
Hmmm, did you install VTK properly using rosdep ? Do you have the lib that contains vtkSTLReader::New() ?

**Comment by alphayed** [comment]
I have found a fix as per this [thread](http://answers.ros.org/question/250846/compiling-ros-kinetec-from-source-fails-when-building-image_proc/). @vrabaud  Thank you for the help

**Comment by zsustc** [comment]
First, make sure you have successfully built and installed vtk on your system;

Then,by using command "locate STLReader" or "locate vtkOBJReader" to ensure "vtkOBJReader" or "STLReader" libs are found in some specific directories. If vtkOBJReader or STLReader related files are found. It means that vtk has changed its structure in the new version, e.g. move vtkOBJReader into a sub library vtkIOGeometry, so you have to tell cmake to find vtkIOGeometry if you want to use that class.

Last, modify opencv3/cmake/OpenCVDetectVTK.cmake, for every find_package(VTK QUIET COMPONENTS ... add an entry vtkIOGeometry.

Success!
