### ISSUE TITLE
[camera_calibration] Doesn't work well with mono16 images

### ISSUE THREAD

**Issue by mintar** [ros-perception/image_pipeline#246]
When running `cameracalibrator.py` on a `mono16` image stream, the image appears all white. This is because `cameracalibrator.py` simply clips all gray values to the lowest 256 values:

[calibrator.py:247](https://github.com/ros-perception/image_pipeline/blob/f94bfe7b03397a78cedd2686e8fb69d234b38447/camera_calibration/src/camera_calibration/calibrator.py#L247)

IMO, it should multiply each gray value by 1/256 instead.

I have verified this on my own image data: When I multiply the input image by 1/256 before feeding it into `cameracalibrator.py`, it works.

**Comment by mintar** [comment]
There's an open pull request that solves this issue: #334

**Comment by JWhitleyWork** [comment]
Closed by #334.
