### ISSUE TITLE
depth_image_proc/point_cloud_xyz subscribed topics

### ISSUE THREAD

**Issue by jdeeee** [ros-perception/image_pipeline#250]
Hi!

Why does depth_image_proc/point_cloud_xyz expect a rectified depth image? Rectified to what? Does that basically mean undistorted in this context? How would you easily get this "rectified" image for a given raw-depth-image?

Thanks!

**Comment by SteveMacenski** [comment]
Rectified means undistorted, you have to undistort it to use the projections
