### ISSUE TITLE
Failing checkerboard detection in camera_calibrator.py

### ISSUE THREAD

**Issue by steve3nto** [ros-perception/image_pipeline#255]
I was wondering if there is a better checkerboard detector to substitute the one that is being used in the camera_calibrator.py node.

This is because when trying to calibrate a stereo camera with a checkerboard with squares of 108 mm the checkerboard is not detected for distances larger than 5 meters. And I really need to calibrate for objects that are farther away of 5 meters.

This is because the calibration is absolutely impossible to carry out for distances larger than 5 meters. The rospy node just does not detect the checkerboard anymore, even though I am using a checkerboard with 108 mm of square size which is quite big. 

With Matlab the checkerboard is detected for much larger distances, so I am sure that having a better algorithm to detect the corners of the checkerboard would help.

What would be the best strategy to detect the checkerboard also for large distances? Is this being developed already by someone? 

Thanks for your help!

---------------------------    EDIT   ---------------------------------  
I went through the calibration procedure in the image_pipeline

https://github.com/ros-perception/image_pipeline/blob/indigo/camera_calibration/src/camera_calibration/calibrator.py

There is an hard-coded threshold in the is_good_sample method that might be rejecting too many good checkerboard detections. That is one ting that might be improved, modified.

Another problem is the downsample and detect approach, in which the images are scaled back to VGA resolution and then detections are upsampled to original size.  I think that really makes it impossible to have good detection for distant objects and it should be avoided for high quality camera calibration.

Has anyone tried to get rid of the downsample and detect method? Is the checkerboard detected better without it? Does it become too slow?

**Comment by SteveMacenski** [comment]
PRs welcome to improve but replacement of the board isn't much of a "bug" as much as a wishlist feature
