### ISSUE TITLE
[ERROR] [1488978654.581949772, 706.250000000]: Expected data of type [16UC1], got [32FC1]

### ISSUE THREAD

**Issue by CuiYawen** [ros-perception/image_pipeline#258]
when I launch the nodelet named convert_metric in a terminal,the message /image will published. When I input “rostopic echo /image" in another terminal,,the error would happen in the first terminal. What's the problem?
error：
[ERROR] [1488978654.581949772, 706.250000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978656.649884033, 708.280000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978658.881251666, 710.350000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978660.976543548, 712.390000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978663.016623712, 714.430000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978665.031236807, 716.430000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978667.149680250, 718.440000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978669.232347782, 720.520000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978671.255612894, 722.550000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978673.266602142, 724.560000000]: Expected data of type [16UC1], got [32FC1]
[ERROR] [1488978675.313160281, 726.600000000]: Expected data of type [16UC1], got [32FC1]

**Comment by SteveMacenski** [comment]
Your problem is that your image is encoded with `32FC1` but the program was expecting a `16UC1`. I suspect your image encoding was incorrect as this nodelet supports both formats. 

I'll leave this ticket open for a week if its still an issue and we can resolve.
