### ISSUE TITLE
Test in camera_calibration/test/directed.py is failing (indigo branch)

### ISSUE THREAD

**Issue by cellard0or** [ros-perception/image_pipeline#259]
The asserts in lines [127](https://github.com/ros-perception/image_pipeline/blob/indigo/camera_calibration/test/directed.py#L127) and [267](https://github.com/ros-perception/image_pipeline/blob/indigo/camera_calibration/test/directed.py#L267) are currently failing. I cannot say why yet. I am using ROS kinetic, maybe the compatibility broke unnoticed recently? The system has ros-kinetic-opencv3 version 3.2.0 installed.

I also tested on a system with ros indigo (and ros-indigo-opencv3 version 3.1.0) installed and the test succeeds there. Something broke while updating opencv3 from 3.1.0 to 3.2.0 it seems.

**Comment by cellard0or** [comment]
The values differ only slightly from the expected ones but I am wondering whether your build and test system also has the tests failing.
[This naive commit](https://github.com/cellard0or/image_pipeline/commit/3c82bfd823fda50fe586c1849b441053486e87bd) would make the tests pass again. This may be no optimal solution as the values might break again easily but I hope it clarifies the problem :)

**Comment by JWhitleyWork** [comment]
@cellard0or - I'm sure this is far behind you now, but is this still an issue for you?

**Comment by cellard0or** [comment]
This problem never came up again, so I consider it fixed ;)
Thanks for asking!
