### ISSUE TITLE
Missing documentation for image_publisher

### ISSUE THREAD

**Issue by trainman419** [ros-perception/image_pipeline#262]
image_publisher looks like a nice package, but there's nothing on the ROS wiki about it. It would be very nice if there was a bit of documentation.

cc @k-okada since it looks like he was the original author

**Comment by k-okada** [comment]
ok, done -> http://wiki.ros.org/image_publisher, we need https://github.com/ros-perception/image_pipeline/pull/263 to have link from image_pipeline page

**Comment by vrabaud** [comment]
Fixed by #263
