### ISSUE TITLE
Depth registration should interpolate when the depth image is smaller than the rgb image

### ISSUE THREAD

**Issue by danmou** [ros-perception/image_pipeline#265]
As it is now, each pixel in the depth image is projected to one pixel in the registered image. This is a problem because the registered image has the same size as the color image, which is often larger than the depth image.

Example:
With the Intel Realsense R200 depth camera you could have a depth resolution of 320x240 and a color resolution of 640x480.
Here is a registered depth image of a wall (which has nearly complete coverage in the original depth image):
![image2](https://cloud.githubusercontent.com/assets/7031745/24854259/0d5335c6-1dde-11e7-9672-50aaf28b4d07.png)
Because of the registration, only 1/4 of the pixels on the wall now have depth data, the rest are zero.
This causes problems with SLAM software such as RTABMAP, which will discard the visual features found in the color image if they do not have a valid depth associated with them, effectively causing 3/4 of the features to be discarded unnecessarily.

There is already a todo note in the [code](https://github.com/ros-perception/image_pipeline/blob/indigo/depth_image_proc/src/nodelets/register.cpp#L215):
`/// @todo When RGB is higher res, interpolate by rasterizing depth triangles onto the registered image`
although I am not sure what the proposed solution entails. Another option would be to scale the image before registration.

**Comment by SteveMacenski** [comment]
PRs welcome, however scaling the image before registration would be a similar (if not exactly the same) process as interpolating point values between pixels to accomplish the same thing. 

This could be implemented as a nodelet chain of resize->registration, or could add the interpolation capability inside of registration itself.

**Comment by machinekoder** [comment]
Thanks for the explanation. Is there more info on the `resize` operation? `image_proc` is sparsely documented.

**Comment by lucasw** [comment]
Unless I'm missing something this is solved by the `fill_upsampling_holes` param from #363

**Comment by mikeferguson** [comment]
Appears this is now supported by linked merged PR
