### ISSUE TITLE
Vertical misalignment of registered depth image compared to rectified RGB image

### ISSUE THREAD

**Issue by mindThomas** [ros-perception/image_pipeline#272]
This is a referenced issue from https://github.com/intel-ros/realsense/issues/233
Though the experienced problems are related to the registration process within the "depth_image_proc" code.

### System Configuration
| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Yocto               |
| Kernel                | 4.4.3-yocto-standard                |
| ROS                   | indigo                    |
| ROS RealSense         | 1.8.0                |
| librealsense          | 1.12.1   (system lib)                |
| Camera Type-Firmware  | R200-1.0.71.06            |

### Expected Behavior
I would expect /camera/rgb/image_rect_color and /camera/depth_registered/sw_registered/image_rect_raw to be aligned.

### Actual Behavior
Please download the pictures below and try to match them (with transparancy).
![rgb-image_rect_color](https://cloud.githubusercontent.com/assets/1436465/24958742/b1d8931c-1f90-11e7-8efc-028a585f8fe5.png)
![depth_registered-image_rect_raw](https://cloud.githubusercontent.com/assets/1436465/24958745/b4678e12-1f90-11e7-891e-28de04278b5e.png)

Doing a transparent matching of the above test images results in the following horizontally mismatched picture.
![horizontal-mismatch](https://cloud.githubusercontent.com/assets/1436465/24958974/7fb5ff5e-1f91-11e7-8d40-d0b05635dfa3.png)
Notice how the registered depth image has a 9 pixel tall black area in the top and a 20 pixel black bar in the right side. If the registered depth image is just moved 9 pixels upwards the color and depth image seem to match much better.
![improved-matching](https://cloud.githubusercontent.com/assets/1436465/24959025/b4f284ee-1f91-11e7-8c36-e063b95a40ae.png)

The misaligned registered depth image results in a misaligned registered pointcloud as shown below with a different model.
![chair_misaligned](https://cloud.githubusercontent.com/assets/1436465/25135487/ca9d89ae-2452-11e7-9a0c-394659dd5818.png)

### Steps to Reproduce
Launch the rgbd nodelet.
`roslaunch realsense_camera r200_nodelet_rgbd.launch`
Capture images with rqt or similar

**Comment by k-okada** [comment]
I think this is the problem of extrinsic parameters provided from realsense driver, and (maybe) fixed by https://github.com/intel-ros/realsense/issues/233#issuecomment-361920190

**Comment by SteveMacenski** [comment]
Intel issue fixed, closing
