### ISSUE TITLE
Fixed number of distortion_coefficients in yaml-output

### ISSUE THREAD

**Issue by NikolasE** [ros-perception/image_pipeline#278]
calibrator.py (~l 475)
def lryaml(self, name, d, k, r, p):
...

```
        + "distortion_model: " + ("rational_polynomial" if d.size > 5 else "plumb_bob") + "\n"
        + "distortion_coefficients:\n"
        + "  rows: 1\n"
        + "  cols: 5\n"
```

When writing the distortion_model, the length of the distortion vector is checked, but two lines later, it's value is fixed to 5 which will lead to problems, if someone really uses the "rational_polynomial"-Model

**Comment by k-okada** [comment]
@NikolasE you're right , I have added patch for this, https://github.com/ros-perception/image_pipeline/pull/341, if you have calibration file using rational_polynomial, please check that.
