### ISSUE TITLE
Kinect2 shows nothing from image_view

### ISSUE THREAD

**Issue by doublexxking** [ros-perception/image_pipeline#280]
Hi everyone, 
I try to use kinect2 to detect my object and my os is Ubuntu 14.04 indigo.  
After I run roslaunch kinect2_bridge kinect2_bridge.launch and  rosrun image_view image_view image:=/kinect2/qhd/image_color,  I got an empty window as shown following:
![screenshot from 2017-06-20 13 04 44](https://user-images.githubusercontent.com/11947126/27345843-10cb921c-55b9-11e7-8bf7-4ce3267308d7.png)

Then I use rostopic list and get:
/rosout
/rosout_agg
rmal@RMAL-ASUS:~/catkin_ws$ rostopic list
/kinect2/depth/camera_info
/kinect2/depth/image
/kinect2/depth/image/depth_compressed
/kinect2/depth_rect/camera_info
/kinect2/depth_rect/image
/kinect2/depth_rect/image/depth_compressed
/kinect2/depth_scaled/camera_info
/kinect2/depth_scaled/image
/kinect2/depth_scaled/image/depth_compressed
/kinect2/depth_scaled/points
/kinect2/depth_scaled_registered/camera_info
/kinect2/depth_scaled_registered/image
/kinect2/depth_scaled_registered/image/depth_compressed
/kinect2/ir/camera_info
/kinect2/ir/image
/kinect2/ir/image/compressed
/kinect2/ir_rect/camera_info
/kinect2/ir_rect/image
/kinect2/ir_rect/image/compressed
/kinect2/mono/camera_info
/kinect2/mono/image
/kinect2/mono/image/compressed
/kinect2/mono_rect/camera_info
/kinect2/mono_rect/image
/kinect2/mono_rect/image/compressed
/kinect2/mono_scaled/camera_info
/kinect2/mono_scaled/image
/kinect2/mono_scaled/image/compressed
/kinect2/rgb/camera_info
/kinect2/rgb/image
/kinect2/rgb/image/compressed
/kinect2/rgb_rect/camera_info
/kinect2/rgb_rect/image
/kinect2/rgb_rect/image/compressed
/kinect2/rgb_scaled/camera_info
/kinect2/rgb_scaled/image
/kinect2/rgb_scaled/image/compressed
/rosout
/rosout_agg

So, My window is empty due to /kinect2/hd/... /kinect2/qhd/... are not published, right?
If so, could some one give me some ideas so that I can get the image correctly?
I will be very appreciated for your help!!

**Comment by k-okada** [comment]
i think https://github.com/code-iai/iai_kinect2/tree/master/kinect2_bridge is the best place for this question.
