### ISSUE TITLE
 "lin" appearing on the top right corner of the calibration screen mean

### ISSUE THREAD

**Issue by SubMishMar** [ros-perception/image_pipeline#282]
![screenshot from 2017-07-08 21-43-18](https://user-images.githubusercontent.com/28704031/27988649-37216faa-6427-11e7-94fa-82ca530312b6.png)
What does  "lin" mean and what does it signify?

**Comment by vrabaud** [comment]
It is the linear error. Feel free to update the wiki with this info if it is not there.

**Comment by SubMishMar** [comment]
@vrabaud  and how much linear error is acceptable ? and what is the unit?? pixel?  

I will update the wiki.

**Comment by k-okada** [comment]
I think this is pixel, and acceptance rate is depending on applications, but < 1.0 might be good.

**Comment by waiyc** [comment]
what is the difference between linear error and re-projection error ?

**Comment by SteveMacenski** [comment]
Closing, question answered
