### ISSUE TITLE
/depth_image_proc/register publishing /depth_registered/image_rect and subscribe fails

### ISSUE THREAD

**Issue by huangyuantao1992** [ros-perception/image_pipeline#284]
Hi,
  I write a launch file for depth_image_proc/register to register the depth image on rgb image's frame. And there are topics such as /depth_registered/camera_info /depth_registered/image_rect /depth_registered/image_rect/compressed /depth_registered/image_rect/compressed/parameter_descriptions /depth_registered/image_rect/compressed/parameter_updates and so on.

But here is the problem that when I subscribe the /depth_registered/image_rect in my own program and do some processing, the registered image can't be shown.
    I can't figure out the problem, anyone help? Thanks!
[launch_file.txt](https://github.com/ros-perception/image_pipeline/files/1145848/launch_file.txt)

**Comment by vrabaud** [comment]
This is not a bug, please ask your question on http://answers.ros.org/questions/
