### ISSUE TITLE
import cv2 ImportError: libvpx.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by doisyg** [ros-perception/image_pipeline#287]
Hello,
I have a dependency error on kinetic and ubuntu 16.04.
Any idea where it is coming from? I did not install opencv from source.
`
import cv2 ImportError: libvpx.so.3: cannot open shared object file: No such file or directory`

Edit: the error appears when running the camera calibration node

**Comment by epiception** [comment]
Did you try running `sudo apt-get install libvpx3` in a new terminal window?

**Comment by doisyg** [comment]
Yes:
```
$ sudo apt-get install libvpx3
[sudo] password for gd: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvpx3 is already the newest version (1.6.0-561-g065ba0c-1).
libvpx3 set to manually installed.
```

And the installed files (no libvpx.so.3):

```
 $ sudo dpkg -L libvpx3
/.
/usr
/usr/local
/usr/local/lib
/usr/local/lib/libvpx.so.4.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libvpx3
/usr/share/doc/libvpx3/changelog.gz
/usr/local/lib/libvpx.so.4
/usr/local/lib/libvpx.so.4.0
```

**Comment by vrabaud** [comment]
You must have libvpx from somewhere else (maybe a ppa).
These are the official version:
https://packages.ubuntu.com/xenial/arm64/libvpx3/filelist
Your solution is to recompile OpenCV (you can include it in your catkin workspace).

**Comment by doisyg** [comment]
Thanks a lot!
It was indeed fetching the package from a ppa that I completly forgot to remove from my source list
