### ISSUE TITLE
Disparity Map shown, but no pointcloud msg is published using stereo_image_proc

### ISSUE THREAD

**Issue by jomocl** [ros-perception/image_pipeline#290]
I am getting a disparity Image and rectified images from the stereo_image_proc it is launched using:

<node name="stereo_image_proc" pkg="stereo_image_proc" type="stereo_image_proc" output="screen" ns="claas_camera_node" >
</node>
<node name="stereo_cam" pkg="image_view" type="stereo_view" output="screen" >
<remap from="stereo" to="/claas_camera_node"/>
<remap from="image" to="image_rect_color" />
</node>	

but looking in rviz there is nothing published on the pointcloud message?

**Comment by paulsammut** [comment]
Load up rqt_graph and make sure that stereo_image_proc node looks good with all necassary messages going to it. 

Then, run make sure that the point cloud topic is being published. Run this command:

rosparam echo /name/of/point/cloud/topic 

A possible issue is that the frame associate with your laser scans isn't properly setup with tf. Good luck!

**Comment by syediu** [comment]
> I am getting a disparity Image and rectified images from the stereo_image_proc it is launched using:
> 
> but looking in rviz there is nothing published on the pointcloud message?

Hello @paulsammut  have you been able to solve this problem? I am also getting disparity images but unable to display pointcloud. my poincloud topic only returns consistent same values and in rviz I can only see a small dot. please let me know if you know what mistakes I made. regards

**Comment by SteveMacenski** [comment]
Closing this issue from inactivity (and probably resolved after 2 years).

**Comment by nick-paul** [comment]
I am having a similar issue with the current version of `stereo_image_proc` A point cloud is published with the correct transform but only a single point is visible at the origin of the transform in rviz.

These unanswered questions on answers.ros.org are describing the same issue and go into a bit more detail:

  - https://answers.ros.org/question/333144/stereo_image_proc-does-not-generate-pointcloud/
  - https://answers.ros.org/question/321282/disparity-image-is-displayed-but-pointcloud-shows-only-a-small-dot-in-rviz/

This bag contains raw camera messages and the generated point clouds:
[points_and_cams.bag.zip](https://github.com/ros-perception/image_pipeline/files/3979506/points_and_cams.bag.zip)

Any idea what the problem might be?
Thanks

**Comment by leander-dsouza** [comment]
I have faced the exact same issue in Gazebo and have answered one of the questions mentioned by @nick-paul **[here](https://answers.ros.org/question/321282/disparity-image-is-displayed-but-pointcloud-shows-only-a-small-dot-in-rviz/?answer=381311#post-id-381311)**. 

*Please let me know in case this solution doesn't work out for you.*

**Comment by JMadhup** [comment]
@leander-dsouza my hackBaseLine is already set to 0.07, I have tried other values as well. I am getting the disparity image but still cannot visualize the point cloud in rviz

**Comment by leander-dsouza** [comment]
This might seem trivial, but are you using ROS2? as the `hackBaseline` parameter changes its alias to `hack_baseline`.

**Comment by JMadhup** [comment]
I am using ROS noetic
