### ISSUE TITLE
No effect after camera calibration

### ISSUE THREAD

**Issue by simubhangu** [ros-perception/image_pipeline#294]
Hi,
 I had tried to calibrate the camera many times. I take 50 -150 sample each time any try to calibrate. It successfully creates all metrics(in terminal). But after commit the result it doesn't affect the view/frames. camera view, looks same as before the camera calibration. My camera resolution is 1280 X 720 at 60 fps. I followed the process given on [(http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration)].

I also checked the content in ".ros/camera_info/head_camera.yaml". This file contains the same Matrices generated by the "cameracalibartion.py".

What should I do to overcome this problem ??

**Comment by trigal** [comment]
does the published image message contain the calibration? i think is more like an issue for ros-answers than a bug here
