### ISSUE TITLE
Node classes cannot be imported

### ISSUE THREAD

**Issue by davelkan-zz** [ros-perception/image_pipeline#300]
Several classes are implement in the nodes directory of camera calibration. This adds no value that i'm aware of over placing them in the src directory while making it very difficult to import these classes in a standard ros set up. A current project i am working on benefits from importing some of these classes, so I have pulled moved the classes to an importable location. Please check out the pr https://github.com/ros-perception/image_pipeline/pull/298

**Comment by vrabaud** [comment]
Fixed in commits mentioned in https://github.com/ros-perception/image_pipeline/pull/298
