### ISSUE TITLE
Error with OpenCV

### ISSUE THREAD

**Issue by GonzMG** [ros-perception/image_pipeline#321]
When I compile, I have this error:

/opt/ros/kinetic/include/opencv-3.3.1/opencv2/core/mat.hpp:2150:50: error: no type named ‘channel_type’ in ‘class cv::DataType<unsigned int>’
     typedef typename DataType<_Tp>::channel_type channel_type;

How can I fix it?

**Comment by JWhitleyWork** [comment]
New maintainer here - I'm assuming this issue is long past. Please confirm and I will close.

**Comment by SteveMacenski** [comment]
This is an openCV issue not a image_pipeline issue
