### ISSUE TITLE
[ WARN] [1522489818.929206010]: [image_transport] Topics '/zed/right/image_mono' and '/zed/right/camera_info' do not appear to be synchronized.

### ISSUE THREAD

**Issue by jediofgever** [ros-perception/image_pipeline#323]
Hi, 
I am trying to get point clouds from zed camera but I got this warning on terminal and no point clouds present on rviz. I did some googling and found that that is caused by non sycned topics. I tried to place 
`
    <param name="approximate_sync" value="true"/>
    <param name="queue_size" value="10"/>
`
to sync the topics but the error still remains when I run `roslaunch stereo_image_proc some.launch`

here is what I have in `some.launch` file 

```
<launch>

  <!-- Start a nodelet manager; the name must be unqualified here -->
  <node pkg="nodelet" type="nodelet" name="pipeline" args="manager" />

  <!-- Include the stereo_image_proc.launch file and pass in a qualified manager name -->
  <include file="$(find stereo_image_proc)/launch/stereo_image_proc.launch" ns="zed">
    <arg name="manager" value="/pipeline" />
  </include>

</launch>
```
How I can overcome this issue and get my point clouds published ? 

Thanks

**Comment by k-okada** [comment]
hi, I think you have to set `approximate_sync` param within `disparity` or  `point_cloud2` namespace, please look at https://github.com/ros-perception/image_pipeline/pull/338 and use them like
```
	<!-- Include the stereo_image_proc.launch file and pass in a
             qualified manager name -->
          <include file="$(find
	                 stereo_image_proc)/launch/stereo_image_proc.launch"
                   >
            <arg name="manager" value="/pipeline" />
            <arg name="approximate_sync" default="true" />
          </include>
```
