### ISSUE TITLE
Camera calibration introduces large change of aspect ratio

### ISSUE THREAD

**Issue by nalt** [ros-perception/image_pipeline#324]
Camera calibration ignores the aspect ratio when it creates the projection matrix. This mainly affects cameras with a wide angle lens and a strong distortion. For some cameras, I got a difference of 30% in focal length for x/y in the projection_matrix. This translates to a rectified image with an incorrect aspect ratio. Since most computer vision algorithms (SIFT, KLT, etc.) cannot cope with such large changes in the aspect ratio, there should be an option to fix it.

The change of aspect ratio is introduced by cv2.getOptimalNewCameraMatrix. It seems it tries to find the largest rectangle that has no unknown/black areas, ignoring the aspect ratio of that rectangle.

Note this is not about the camera_matrix, which usually exhibits similar focal lengths in x/y. Also, the argument --fix-aspect-ratio allows to fix the aspect ratio in camera_matrix, but not in projection_matrix.

It would be interesting in what values other users get for the focal lengths in projection_matrix. Ideally, this could be fixed in OpenCV of course.

**Comment by mikeferguson** [comment]
This ticket predates support for fisheye calibration, which I believe would serve as an alternative approach that likely solves this?
