### ISSUE TITLE
Camera calibration should ignore frames with large motion (mainly for rolling shutter)

### ISSUE THREAD

**Issue by nalt** [ros-perception/image_pipeline#325]
Camera calibration takes images out of the video stream while the camera is moving. This means that slightly blurred images are used for calibration, which reduces the location accuracy of the corners points. Even worse, for rolling shutter cameras, the locations of corner points get shifted. This shift easily amounts to several pixels between the upper and the lower part of the pattern.

I noticed that calibration results differ a lot between several runs with rolling shutter cameras. A quick test revealed that this changes as soon as frames with large motion are rejected.

Did anyone see similar problems?

**Comment by jack-digilabs** [comment]
I had a horrible problem with my "calibrated camera" being so off, that in RVIZ, it appeared to be pitching down 15 degrees in RVIZ. This caused issues like poor aruco marker detections who's axis sputtered and flipped around as well as detections that should have been straight ahead of the robot appearing 1 meter underground.

My Solution: Cover calibration board with hand until the board is steady then remove hand until a image was taken (prints out in terminal). Then recover board with hand and move to the next spot.

Life gets much easier when the cameras are calibrated properly. Possibly helpful to #356 and #281.

**Comment by JWhitleyAStuff** [comment]
@nalt - I know this is an old issue but do you have any suggestions on how we might implement the rejection using an algorithm? (or, better yet, a PR implementing it)
