### ISSUE TITLE
rectification performed

### ISSUE THREAD

**Issue by MPForte** [ros-perception/image_pipeline#327]
Does anyone know which kind of algorithm is used for the rectification of the images in `image_proc`?

**Comment by lucasw** [comment]
https://github.com/ros-perception/image_pipeline/blob/indigo/image_proc/src/nodelets/rectify.cpp#L154

->

https://github.com/ros-perception/vision_opencv/blob/kinetic/image_geometry/src/pinhole_camera_model.cpp#L293

->

https://docs.opencv.org/3.3.1/da/d54/group__imgproc__transform.html#gab75ef31ce5cdfb5c44b6da5f3b908ea4

->

https://github.com/opencv/opencv/blob/4d7d630e925bad6a7b1584c7d792b938faf0829b/modules/imgproc/src/imgwarp.cpp#L1668

**Comment by MPForte** [comment]
Thank you!!
Do you know if there's a built-in function to project the 3D points in rectified images back to the unrectified images?

**Comment by lucasw** [comment]
Take a look at cv::projectPoints()

https://docs.opencv.org/3.3.1/d9/d0c/group__calib3d.html#ga1019495a2c8d1743ed5cc23fa0daff8c

Also I see PinholeCameraModel::unrectifyPoint :

https://github.com/ros-perception/vision_opencv/blob/0b36ea7a6f40fc05d54e3e6871933129687d5cc4/image_geometry/src/pinhole_camera_model.cpp#L349

**Comment by MPForte** [comment]
Thank you!!
