### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-perception/image_pipeline#328]
All of the dependencies for this package are now available in Melodic, so it would be great to get this package released there.  Thanks in advance!

**Comment by clalancette** [comment]
Ping, can we get this released into Melodic?  Thanks.

**Comment by k-okada** [comment]
@vrabaud had released last week.
https://github.com/ros/rosdistro/pull/17801

**Comment by clalancette** [comment]
Thank you!
