### ISSUE TITLE
filename_format parameter cannot by given convention

### ISSUE THREAD

**Issue by tik0** [ros-perception/image_pipeline#330]
I use the image_saver node to store images.
Unfortunately, the syntax described in the [wiki](http://wiki.ros.org/image_view#image_view.2BAC8-diamondback.image_saver) does not work, due to parameter server issues.
When I execute `rosrun image_view image_saver filename_format:=cam_%04d.png`, the parameter server says:

```
terminate called after throwing an instance of 'ros::InvalidNameException'
  what():  Character [%] at element [4] is not valid in Graph Resource Name [cam_%04d.png].  Valid characters are a-z, A-Z, 0-9, / and _.
Aborted (core dumped)
```

**Comment by k-okada** [comment]
hi, that's parameter, so you should type
```
rosrun image_view image_saver _filename_format:=cam_%04d.png
```

**Comment by tik0** [comment]
You're right, thanks for the reply!
