### ISSUE TITLE
How to make the name of image with the timestamp?

### ISSUE THREAD

**Issue by andiconda** [ros-perception/image_pipeline#335]
I  transfer the .bag into the image. but I want to make the image with time information. so  I want to put the timestamp into the image's name.
I try
 `rosrun image_view extract_images _sec_per_frame:=0.01 filename_format:="chuang.jpg" image:=/optris/thermal_image_view`
but the name still is "frame1.jpg  frame2.jpg......"
for filename_format:="chuang.jpg", what should I do?

**Comment by wkentaro** [comment]
Please see https://github.com/ros-perception/image_pipeline/pull/203, it added the feature which you need.
