### ISSUE TITLE
camera calibration does not compute the vertical shift

### ISSUE THREAD

**Issue by MPForte** [ros-perception/image_pipeline#342]
I would like to know how it is possible to have also the vertical shift between my images. The camera calibration is only giving me the horizontal one but my cameras are offset also in the y-axis, so my Ty in the right camera calibration file should not be 0.
Thanks!

**Comment by JWhitleyWork** [comment]
@MPForte - Is this something that you still need?

**Comment by SteveMacenski** [comment]
@MPForte can you describe more in the context here? I can't really dissect what you're trying to get at.

**Comment by SteveMacenski** [comment]
Closing from non-response
