### ISSUE TITLE
Monocular camera calibration at different resolution/ratio

### ISSUE THREAD

**Issue by dcazzato** [ros-perception/image_pipeline#344]
Hello,

I am trying to use the camera_calibrator node with the cameracalibrator.py script. I would like to calibrate cameras working at different resolution or ratio. I am wondering if modifying the following line:

`display = cv.CreateMat(max(480, height), width + 100, cv.CV_8UC3)`

is enough to achieve such results, and why there is no command line option to set the window and image resolution.

Thank you

**Comment by JWhitleyWork** [comment]
@dcazzato - Is this something that you still need?

**Comment by dcazzato** [comment]
No thanks, I better understood the tool and I was able to properly use and modify it.
