### ISSUE TITLE
How to use pointcloud for octomap_mapping?

### ISSUE THREAD

**Issue by sammyjan** [ros-perception/image_pipeline#348]
Hi,I want to use the pointcloud data and the octomap_mapping package to build real-time octomap. So I change the frame_id and pointclud topic in the launch document ,but I can't see any octomap in the rviz. How can I solve it?Thanks!
(My English isn't well,sorry)

**Comment by SteveMacenski** [comment]
Hi,
This doesn't relate to the `image_pipeline` metapackage or any of its contents. I would recommend checking ROS tutorials, particularly roslaunch remapping.
