### ISSUE TITLE
depth_image_proc nodelets won't subscribe any topics?

### ISSUE THREAD

**Issue by huangzonghao** [ros-perception/image_pipeline#350]
For some reason the nodelets in depth_image_proc won't subscribe any topics? (aka not taking any inputs) If `rosnode info` the corresponding node, the subscription list in `None`.

The behavior consists no matter whether I launch the nodelet in a launch file or simply calling rosrun.

What am I missing here?

**Comment by lennarthaller** [comment]
Just stumbled upon this, in case its still a problem for you or anyone else, [here](https://answers.ros.org/question/291590/depth_image_proc-subscriber/) is the answer.

**Comment by SteveMacenski** [comment]
Thanks @lennarthaller, closing
