### ISSUE TITLE
depth_image_proc has a broken conditional when checking supported encodings

### ISSUE THREAD

**Issue by SJamieson** [ros-perception/image_pipeline#353]
I receive an error `Depth image has unsupported encoding [mono16]` when trying to convert mono16 images to point clouds. I believe the issue is an incorrect conditional, described below.

A [conditional statement in point_cloud_xyzi.cpp](https://github.com/ros-perception/image_pipeline/blob/8d01c930e66bdeb58c4b138539a64ddea0b17e10/depth_image_proc/src/nodelets/point_cloud_xyzi.cpp#L202) checks that `intensity_msg->encoding != enc::MONO8 || intensity_msg->encoding != enc::MONO16`, which always evaluates to `true` since `"mono8" != "mono16"`. I assume that it was intended to check `&&` instead of `||`. I have submitted a pull request that applies this fix: #352

**Comment by JWhitleyAStuff** [comment]
Closing issue in favor of discussion in PR.
