### ISSUE TITLE
ros2 bloom release

### ISSUE THREAD

**Issue by yechun1** [ros-perception/image_pipeline#370]
@mjcarroll  As image_common be released in [crystal rosdistro](https://github.com/ros2/rosdistro/pull/376)  ,  there should be no dependence block for ros2 image_pipeline/image_depth_proc release. I would also like to add image_depth_proc from image_pipeline in this Crystal release, but I cannot to run bloom-release for this package, sync I have no permission to create a tag on image_pipeline project. Will you please help to maintain this package's releasing?

**Comment by mjcarroll** [comment]
I'll go ahead and create the tag, and then you can cut a release.  Is it only for `image_depth_proc` or are the other packages in `image_pipeline` that need to get released?

**Comment by yechun1** [comment]
image_publisher, image_view and image_proc portings are completed, would you please help to review the PR of [image_view](https://github.com/ros-perception/image_pipeline/pull/365)and [image_proc](https://github.com/ros-perception/image_pipeline/pull/369), and we could have quick issue fixing.
for image_publisher, I'll try to fix TODO in it very soon.

**Comment by yechun1** [comment]
or could I use below code temporary, would you give me a suggests. thanks.

~~_rclcpp::Node::SharedPtr node = std::shared_ptr<rclcpp::Node>(this);~~
~~camera_info_manager::CameraInfoManager(node);_~~

this will leader invalid pointer.

**Comment by yechun1** [comment]
@mjcarroll what's the deadline for crystal, currently image_depth_proc and image_pubisher are ready for release. and we may need two more days at least to fix/review/merge image_view and image_proc next workday. If there is no time for image_view and image_proc, please help to create a tag, and I could first release depth_image_proc and image_publisher. And interate other packages for next build.

**Comment by mjcarroll** [comment]
I went ahead a did a release of image_depth_proc and image_publisher, since they are good to go, there is no reason we can't do another release before Wednesday or so.

**Comment by yechun1** [comment]
image_pipeline has been released on ros2distro, closed this issue.
