### ISSUE TITLE
Everything works fine, but the program does not start to calibrate

### ISSUE THREAD

**Issue by YingjieLu** [ros-perception/image_pipeline#381]
It happens for both mono and stereo calibration on my laptop. The calibration file is running without any error message, and the image stream collected by camera pops up, but the image stream does not have lines connecting squares in checkerboard, and the calibration at different directions is also not shown. The command line looks like:

`rosrun camera_calibration cameracalibrator.py --size 8x8 --square 0.04 right:=/camera/right/image_raw left:=/camera/left/image_raw left_camera:=/camera/left right_camera:=/camera/right --no-service-check`

I checked the timestamp, left and right cameras are well synchronized, and I tried `--approximate` as well, but nothing works.
It happens to mono camera as well, same issue.

**Comment by klintan** [comment]
Make sure the size and square is correct as stated in the tutorial: 

> Calibration uses the interior vertex points of the checkerboard, so an "8x6" board is nine squares wide and seven high, like the example below.

I put in the checkboard size 9x7 in this case by accident, and no lines will show up if its the incorrect size/no of squares.

**Comment by YingjieLu** [comment]
> Make sure the size and square is correct as stated in the tutorial:
> 
> > Calibration uses the interior vertex points of the checkerboard, so an "8x6" board is nine squares wide and seven high, like the example below.
> 
> I put in the checkboard size 9x7 in this case by accident, and no lines will show up if its the incorrect size/no of squares.

Thank you very much, it works!
