### ISSUE TITLE
Remove signals from find_package()

### ISSUE THREAD

**Issue by jwhendy** [ros-perception/image_pipeline#384]
I believe [this issue](https://github.com/ros/ros_comm/pull/1580) also affects you. On arch linux using cmake 3.13 and boost 1.69, I have to [remove signals](https://github.com/ros-perception/image_pipeline/blob/indigo/image_view/CMakeLists.txt#L8) from `CMakeLists.txt` to build this successfully.

**Comment by SteveMacenski** [comment]
@jwhendy I would merge a PR implementing this. I audited the code and don't see anyone using it.

**Comment by SteveMacenski** [comment]
https://github.com/ros-perception/image_pipeline/pull/379 implements

**Comment by SteveMacenski** [comment]
Been merged. Thanks for the report @jwhendy

**Comment by jwhendy** [comment]
Thanks for handling!
