### ISSUE TITLE
image_view output dailog box issue 

### ISSUE THREAD

**Issue by vishalgpt579** [ros-perception/image_pipeline#390]
I've recently started working in ROS & VREP . so for learning purpose , I'm also using a scene .
![screenshot from 2019-03-06 14-27-56](https://user-images.githubusercontent.com/30352891/53868469-1eb5be80-401c-11e9-9e3e-e30bfec3e92d.png)

This scene has vision sensor which act as input. My object was to use that feed and do processing . Firstly, to the see the feed i use...

`rosrun image_view image_view image:=/visionSensor/image_rect _autosize:=True`

![screenshot from 2019-03-06 14-19-05](https://user-images.githubusercontent.com/30352891/53868644-823fec00-401c-11e9-97e1-d00c720a6b15.png)

the output i get is as follows...

![screenshot from 2019-03-06 14-18-59](https://user-images.githubusercontent.com/30352891/53868717-a6033200-401c-11e9-98b0-2b3e68021cc5.png)

which occupies the whole screen and does not resizes... the other way around was to lower the resolution of vision sensor. That gives a smaller output screen(which doesn't helps)

I'll be using multiple output screen ...like this ... so being able to resize them would be a great help. Please excuse me for any typo errors or mistakes of  any sort.

![screenshot from 2019-03-06 14-38-24](https://user-images.githubusercontent.com/30352891/53869156-a18b4900-401d-11e9-92e4-c2a338bb2e8c.png)

**Comment by JWhitleyWork** [comment]
Which version of ROS are you using and on which version of Ubuntu?

**Comment by vishalgpt579** [comment]
> Which version of ROS are you using and on which version of Ubuntu?

@JWhitleyAStuff  I'm using following version of ROS  :

 >rosdistro: melodic
 >rosversion: 1.14.3

 And following version of Ubuntu:

> Distributor ID:	Ubuntu
>Description:	Ubuntu 18.04.2 LTS
>Release:	18.04
>Codename:	bionic

**Comment by JWhitleyWork** [comment]
@vishalgpt579 - What is the original pixel height/width of the image you're trying to display? It looks like the default for `image_view` is to provide a window with 1:1 pixel size of the original image. If the image is larger than your desktop size, what you're seeing would be the result. There are a few ways around this, but they all require changes to the node.

**Comment by vishalgpt579** [comment]
@JWhitleyAStuff, The original pixel height/width of the image is 1280x1024(which is same as of my monitor). As i mentioned in original question , that lowering the resolution provides a smaller windows , i understand it now, which is because of this reason...
>It looks like the default for image_view is to provide a window with 1:1 pixel size of the original image

Could you please describe those ways of sorting this out @JWhitleyAStuff ?

**Comment by JWhitleyWork** [comment]
Here are a couple of options that would work:

1. Provide a "fullscreen" parameter which is a Boolean. If this parameter is "true," then set the output window to be full-screen.
2. Provide a parameter (difficult to think of a name) that, if set to "true," means that if the output image is larger than the desktop area, set the output window to full-screen.
3. Provide a "output scaling" parameter which defaults to 1.0. The output image window would then be the original width and height multiplied by this value.

I think number 3 would solve your issue in the most convenient way but I'm open to suggestions and feedback.

**Comment by SteveMacenski** [comment]
I'd even recommend a 4th one, where the size of the image is taken by the size of the window. Allow the window to rescale anyway it wants then just have the image scale to the smallest dimension

**Comment by JWhitleyWork** [comment]
@vishalgpt579 - PR #389 gives the full-screen option (my option 1) but I'm guessing this doesn't really solve your use-case, correct?

**Comment by vishalgpt579** [comment]
@JWhitleyAStuff @SteveMacenski , thank you for your recommendations. But since I'm just a beginner, all i can infer from your suggestion is either one of the 2 things ...

1) To edit the [launch file ](https://github.com/lrse/whycon/blob/master/launch/whycon.launch) which I'm running , instead of the line 
`rosrun image_view image_view image:=/visionSensor/image_rect _autosize:=True`
and somehow make changes to   _output ="screen"_  on line 14 of [whycon.launch](https://github.com/lrse/whycon/blob/master/launch/whycon.launch)

2) Secondly , To edit the image_view package itself. 

Either of them i have not much of a clue...  could you guide me further?
Please correct me if I'm wrong .

**Comment by vishalgpt579** [comment]
> @vishalgpt579 - PR #389 gives the full-screen option (my option 1) but I'm guessing this doesn't really solve your use-case, correct?

@JWhitleyAStuff ,I tried doing this... 
`rosrun image_view image_view image:=/visionSensor/image_rect _autosize:=True _fullscreen:=False`

Yes, you were correct. It still doesn't works. 

![Screenshot from 2019-04-25 14-33-38](https://user-images.githubusercontent.com/30352891/56724014-c7a0b000-6767-11e9-9b6a-7a6b9490f721.png)

Output  remained the same ... unresizable 

![Screenshot from 2019-04-25 14-33-30](https://user-images.githubusercontent.com/30352891/56724136-08002e00-6768-11e9-84df-b5025634e5f5.png)

**Comment by lamhung81** [comment]
Did you successfully resolve this problem?
