### ISSUE TITLE
Fix travis CI

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/image_pipeline#396]

**Comment by JWhitleyWork** [comment]
@SteveMacenski - For the repositories to which I have maintenance responsibilities, I have been switching to CircleCI which is more flexible, updated considerably more often, and has much lower queue times (see https://github.com/ros-drivers/velodyne/blob/master/.circleci/config.yml and https://circleci.com/gh/ros-drivers/velodyne as an example). Any opposition?

**Comment by SteveMacenski** [comment]
None at all. I haven't used it personally, but that's not a reason _not_ to learn something :)

**Comment by JWhitleyWork** [comment]
Thanks. I'll get on it as soon as I'm back from lunch. :)

**Comment by JWhitleyWork** [comment]
Fixed in #398 by changing to CircleCI and using new build setup. Since Indigo recently EOL'd, we're only running CI on Kinetic and Melodic branches.
