### ISSUE TITLE
Calibration for VREP images

### ISSUE THREAD

**Issue by syediu** [ros-perception/image_pipeline#405]
Hello All, Do I need any sort of calibration if the images are coming from two image sensors on VREP?
I can receive disparity map and pointclouds but the problem is I am unable to visualize poinclouds on rviz so I thought it may be because of the calibration? If anyone has worked on it please help me with this issue. Kind Regards Izzat

**Comment by SteveMacenski** [comment]
I can't say that I've ever used VREP to know if you need to do it. If they're without undistortion then you should probably have the calibration parameters to do so. However without building your application, I dont know what you intend to do with them.

Please ask this on the VREP forums.
