### ISSUE TITLE
image_saver does not save anything if not a camera topic (bare image)

### ISSUE THREAD

**Issue by bricerebsamen** [ros-perception/image_pipeline#41]
could it be possible to detect whether the topic is a camera topic or an image topic, and subscribe accordingly? I'm publishing some intermediate images as bare images and they don't have any camera info associated.

**Comment by max90727** [comment]
I have got an "Invalid arguments" in line 102. How to solve that?

**Comment by vrabaud** [comment]
How are you calling it ?

**Comment by max90727** [comment]
Sorry for the late response.
The problem is solved, it was right. I was coding in Eclipse, the IDE told the code was wrong, but it comes with successful catkin_make. Thanks.

**Comment by vrabaud** [comment]
cool, thx, keeping close then
