### ISSUE TITLE
Sync Problem.

### ISSUE THREAD

**Issue by dava2788** [ros-perception/image_pipeline#42]
Hi.
I'm running ros fuerte. The revision 2863 of GScam. 
I'm trying to get a rectified image to use then for the node viso2. But I have a problem, after I made the calibration. I have a warning:

[image_transport] Topics '/Dava/image_mono' and '/Dava/gscam/camera_info' do not appear to be synchronized. In the last 10s: Image messages received: 80 CameraInfo messages received: 80 Synchronized pairs: 0

The problem is I can't see the rectified image when I Subscribed the topic in image_view.

I put all the details in this link:
http://answers.ros.org/question/84611/synchronized-problem-related-to-calibration/

I will appreciate any respond . Thank you

**Comment by vrabaud** [comment]
@jbohren is the maintainer of gscam.

Fuerte is not supported anymore so I will probably close that bug. Can you please submit your launch file as pure text, not images, easier to debug. What instruction do you run exactly ? thx.

**Comment by jbohren** [comment]
Yeah, try using gscam from the github repo. http://github.com/ros-drivers/gscam

**Comment by dava2788** [comment]
Thanks you can downloaded my launch file in this link:
https://mega.co.nz/#!fohxhQYY!RIuUOVuf1mL8Nn_erxkrujVt8zUmsLn-4_kP2YokMxc

PD: I put this question to the Gscam too

**Comment by vrabaud** [comment]
ok, that seems fixed in the question
