### ISSUE TITLE
Package build fails

### ISSUE THREAD

**Issue by acxz** [ros-perception/image_pipeline#420]
I am trying to build to latest release version of the package 2.0.0. Problems I am encountering right now include having a `signals` dependency. I see that this has been fixed on master, but the fix has not been released. It would be great if this could be released.
After manually making the change, another issue I am encountering is the following:
```
/usr/bin/ld: warning: libopencv_core.so.4.1, needed by /usr/lib/libopencv_videoio.so.4.1.0, may conflict with libopencv_core.so.3.4
/usr/bin/ld: CMakeFiles/video_recorder.dir/src/nodes/video_recorder.cpp.o: in function `callback(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)':
video_recorder.cpp:(.text+0x29f): undefined reference to `cv::VideoWriter::open(cv::String const&, int, double, cv::Size_<int>, bool)'
collect2: error: ld returned 1 exit status
```
Looking around I have noticed that a PR has been merged for opencv 4 support but again it seems to not be in the latest release.
Can these fixes be released, so that the package can build successfully?

**Comment by JWhitleyWork** [comment]
@acxz - The 2.0.0 release is specifically for ROS2. Are you building this in a ROS2 environment or ROS1? I'm just now releasing 1.13.0 for ROS1 Melodic and it should be available on the repos in a couple of weeks at the most.

**Comment by acxz** [comment]
I see, my bad. Yes I am using this package for melodic. I noticed that 1.13.0 has been released and I just tried building that. With the latest release (1.13.0), the signal issue has gone away. But I am still getting the same issue with the opencv warning.

**Comment by acxz** [comment]
Some more helpful information:
I am trying to build image_view (1.13.0) specifically.
opencv version: 4.1
Also have opencv3 installed under opt/

Hmm so after looking around on my system a bit this is what I am surmising.
I have other ros packages installed that depend on opencv3. However, I also have opencv (latest release version) installed and this package tries to use that but is getting confused since I also have opencv3 installed. I am not really sure what the proper fix for this would be, besides moving the packages which depend on opencv3 to depending just on opencv. Or moving this package to depend on opencv3 explicitly instead of opencv.

In any case, it seems like this is not an issue for this repo. If you have any suggestions I would love to hear them, but you can go ahead and close this issue.

**Comment by acxz** [comment]
I ended up fixing the problem on my machine by changing the `OpenCV REQUIRED` in `image-view/CMakeLists.txt` to `OpenCV 3 REQUIRED`. It seems as though even if this package works with opencv I still need to patch it accordingly so I can use this package alongside others that require opencv3 specifically for now. Going ahead and closing this.

**Comment by SalilVishnuKapur** [comment]
@acxz Kindly guide me If I should manually fix all the obsolete opencv syntax to build image_pipeline for opencv 4.1.0? I have no option left to build it with opencv 3. I am building up 10 ros opencv dependent packages and after beating my head with these, I have nearly fixed all the issues except for this image_pipeline package and two others. Now these three packages have just these obsolete naming issues of opencv. I am looking for a quick solution, I am at 82% of building these 10 packages; very close now. Issue : https://github.com/ros-perception/image_pipeline/issues/460

**Comment by acxz** [comment]
@SalilVishnuKapur From what I understand this package should work with opencv4. See #375 
Nvm, opencv4 is not directly supported by this package. I am afraid I cannot help. Although the ArchLinux package for this does build successfully with opencv4. (No source code is changed for this) If you want the latest software packages, I would recommend moving over to ArchLinux, (I would also be able to help you out more directly.)

**Comment by SalilVishnuKapur** [comment]
@acxz Thanks for replying back and I will definitely check Arch linux branch. Actually, I tried to build it with melodic branch of this packages but it failed. And I was able to build image_pipeline with opencv 4.1.0 by fixing it myself, though do read this comment by @SteveMacenski on my posted issue(https://github.com/ros-perception/image_pipeline/issues/460). And now out of the ten ros packages just one is left, ar_track_alvar which is the last one, though I have debugged it but plan to do the fixes by monday. At 94% of building these ten ros packages. But now I want to be part of this open source community, can you please add me as a maintainer to these ros packages? I am ready to take any kind responsibility for these open source ros packages. This is my blog (https://www.geekasservice.com/), I just want to feel the happiness of helping package users through this open source community.

**Comment by acxz** [comment]
Arch Linux is not a branch it is another operating system like Debian or Ubuntu. Arch Linux is rolling release so it always has the most up to date upstream packages at any given time. For example, the default opencv on Arch is opencv4.

You can contribute to open source without being a maintainer. That is one of the beauties of open source, you don't have to "own" or officially be a part of the codebase to submit changes (pull requests (PRs)). Your enthusiasm is much appreciated. You should definitely share your changes on these packages by creating a "fork" of this repository, committing changes to it, and then submitting a PR upstream to the original codebase you forked from. If they are good changes then they would be merged into upstream for everyone to use.
