### ISSUE TITLE
Rotate images

### ISSUE THREAD

**Issue by hachbani2019** [ros-perception/image_pipeline#422]
hi,

I'm trying to setup a stereo vision system from two camera, so for that, I'm using stereo_image_proc node. At first glance, I was getting a good disparity image, but the PointCloud I was getting was not in the right direction (It was on the top of my robot while the obstacle was in front of it). so I changed the orientation of the camera's axis to match the description in the [stereo_image_proc](http://wiki.ros.org/stereo_image_proc). Now, the pointcloud is good, but since I changed the orientation of the cameras, the images I'm getting are rotated, hence, the disparity image I'm getting is not correct.

I'm thinking of changing the [disparity.cpp](https://github.com/ros-perception/image_pipeline/blob/melodic/stereo_image_proc/src/nodelets/disparity.cpp) in order to change the orientation of the left and right images before calculating the disparity image, but I can't figure out a correct way to do it. 

If any of you have a suggestion, I'd be really thankful.

Thanks.

**Comment by SteveMacenski** [comment]
If the orientations are wrong, why not update their positions in its description file / TF to be correct? It seems like you may have some configuration issues in following REPs or data orientations.

Remember this is a pipeline, you can feed in different information to different things, it doesn't need to be a linear path to in->stage->stage->done. It could have multiple paths (one branch rotates, gives you PC, another doesnt and gives you disparity, etc). 

This seems like you just need to put the right blocks in the right order
