### ISSUE TITLE
Link to (willowgarage) OpenCV's block matching

### ISSUE THREAD

**Issue by leafgecko** [ros-perception/image_pipeline#427]
In [http://wiki.ros.org/stereo_image_proc](url), under the Overview point, the link for OpenCV's block matching algorithm, the link [http://opencv.willowgarage.com/documentation/cpp/camera_calibration_and_3d_reconstruction.html#stereobm](url) seems dead.
![deadlink](https://user-images.githubusercontent.com/21381491/60802261-17a9e300-a1ab-11e9-80be-27661070d90b.png)

**Comment by SteveMacenski** [comment]
Thanks for pointing it out, I updated the wiki
