### ISSUE TITLE
Problem with the image_pipeline camera_calibration nodes

### ISSUE THREAD

**Issue by BastiAB** [ros-perception/image_pipeline#44]
Hi community,

I'm trying to use the image_pipeline-package to realize a stereovisual system with ros and opencv.

When I use the node for calibration of one usb-camera I get an error every time I put the chessboard (8x6) in front of the camera and the node freezes. I googled the problem and found two ros-questions similar to my problem. One answer was to install a 64-bit version of ubuntu, and the second one was to remove opencv-files from the ros-libraries and install the original opencv-files instead. Now I'm wondering if theres another way to get rid of my problem and where it comes from. I attached the output of my console below my request.

I,ve also tried to use the stereocalibration from this package and the cpp-tutorial calibration from the OpenCV Tutorials. The result was the same.

I'm currently using Ubuntu 12.04 with ros-hydro-installation.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.0242 image:=/stereo/left/image_raw camera:=/stereo/left Waiting for service /stereo/left/set_camera_info ... OK \* Added sample 1, p_x = 0.931, p_y = 0.486, p_size = 0.349, skew = 0.186 OpenCV Error: Assertion failed (blockSize % 2 == 1 && blockSize > 1) in adaptiveThreshold, file /tmp/buildd/ros-hydro-opencv2-2.4.6-1precise-20130919-0139/modules/imgproc/src/thresh.cpp, line 797 Exception in thread Thread-3: Traceback (most recent call last): File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner self.run() File "/home/faps/catkin_ws/src/image_pipeline/camera_calibration/nodes/cameracalibrator.py", line 68, in run self.function(m) File "/home/faps/catkin_ws/src/image_pipeline/camera_calibration/nodes/cameracalibrator.py", line 134, in handle_monocular drawable = self.c.handle_msg(msg) File "/home/faps/catkin_ws/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 740, in handle_msg scrib_mono, corners, downsampled_corners, board, (x_scale, y_scale) = self.downsample_and_detect(gray) File "/home/faps/catkin_ws/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 410, in downsample_and_detect (ok, downsampled_corners, board) = self.get_corners(scrib, refine = True) File "/home/faps/catkin_ws/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 378, in get_corners (ok, corners) = _get_corners(img, b, refine) File "/home/faps/catkin_ws/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 156, in _get_corners (ok, corners) = cv.FindChessboardCorners(mono, (board.n_cols, board.n_rows), cv.CV_CALIB_CB_ADAPTIVE_THRESH | cv.CV_CALIB_CB_NORMALIZE_IMAGE | cv2.CALIB_CB_FAST_CHECK) error: blockSize % 2 == 1 && blockSize > 1

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by vrabaud** [comment]
This is the same as https://github.com/ros-perception/image_pipeline/issues/43
