### ISSUE TITLE
Stereo calibrate issue with 2 different camera with different focal length and fov

### ISSUE THREAD

**Issue by waiyc** [ros-perception/image_pipeline#445]
Hi,

I am trying to do stereo calibration with color camera and IR camera from intel RealSense D435 camera. However, the stereo calibration process is unable to collect the required amount of image data for calibration due to the focal length and fov are different.

Is there any ways to overcome this issue?

Thanks.

**Comment by SteveMacenski** [comment]
You can independently calibrate their intrinsics before calibrating their extrinsics.
