### ISSUE TITLE
can't save image

### ISSUE THREAD

**Issue by hygxy** [ros-perception/image_pipeline#448]
when I right-click  on the diaplay gui, there is no file named frame0000.jpg, etc. saved as documented here:http://wiki.ros.org/image_view. Instead, the display window is frozen and have to kill the process manually.

**Comment by SteveMacenski** [comment]
Please provide more information. What build, what distro, what OS, etc

**Comment by SteveMacenski** [comment]
Please provide a full description @hygxy

**Comment by hygxy** [comment]
@SteveMacenski  Sorry for no updates, but I don't have access to the camera recently. I will post more details as long as I get the device and reproduce the error. In the meantime, you can close this issue.
