### ISSUE TITLE
Rectify plethora of changes in ROS1 and ROS2 versions 

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/image_pipeline#449]
We've had alot of changes that are targeted at either ROS1 or ROS2 that have been changing quite alot, but nothing to homologate these changes together to make sure we have a consistent set of features and elements between ROS1 and ROS2.

**Comment by mikeferguson** [comment]
List of PRs to review (some might actually be in ROS 2 - but this is everything I see that isn't clearly in ROS 2 when doing a diff between noetic and rolling)
 * [x] #816 
 * [x] #791 
 * [x] #795 
 * [x] #812 (may be needed?)
 * [x] #806
 * [x] #716 (already done)
 * [x] #723
 * [x] #671 
 * [x] #630 
 * [x] #489 
 * [ ] #375 
 * [x] #336

**Comment by mikeferguson** [comment]
https://github.com/ros-perception/image_pipeline/pull/863 ports #816 to ROS 2

**Comment by ahcorde** [comment]
- Add support for floating point fps https://github.com/ros-perception/image_pipeline/pull/866 (rolling)

**Comment by ahcorde** [comment]
- depth_image_proc/point_cloud_xyzi_radial Add intensity conversion (copy) for float https://github.com/ros-perception/image_pipeline/pull/867
 - Support MONO16 image encodings: point_cloud_xyz https://github.com/ros-perception/image_pipeline/pull/868
 - support rgba8 and bgra8 encodings by skipping alpha channel https://github.com/ros-perception/image_pipeline/pull/869
 - Add option to prepend timestamp to image filename in image_saver node: https://github.com/ros-perception/image_pipeline/pull/870
 - Fixing thrown Exception in camerachecker.py https://github.com/ros-perception/image_pipeline/pull/871
 - Add option to use the RGB image timestamp for the registered depth image https://github.com/ros-perception/image_pipeline/pull/872
 - added more aruco dicts, fixed aruco linerror bug  https://github.com/ros-perception/image_pipeline/pull/873
 - resize.cpp: fix memory leak https://github.com/ros-perception/image_pipeline/pull/874

**Comment by mikeferguson** [comment]
@ahcorde - are you planning to do the last one on this list? (OpenCV4 compatibility - possible some of this is already in rolling, which makes it harder to actually resolve the diff)

**Comment by ahcorde** [comment]
> @ahcorde - are you planning to do the last one on this list? (OpenCV4 compatibility - possible some of this is already in rolling, which makes it harder to actually resolve the diff)

I was checking this PR, Humble is supported from Ubuntu Focal and Debian Bullseye which I think we can only install OpenCV4 (not sure about OpenCV3). All the changes are already made, which means that these packages can compile with OpenCV 3 and 4

**Comment by mikeferguson** [comment]
Awesome - in that case - I'll assume we've ported whatever was needed - and AFAICT that means we have feature parity with ROS 1 and ROS 2 and we can close this ticket!
