### ISSUE TITLE
example for setting destination width and height and getting updated camera info when using image_proc/resize

### ISSUE THREAD

**Issue by hygxy** [ros-perception/image_pipeline#454]
Hey, could someone please give me a concrete example about how to use the resize() function via command line? 
This [link](https://github.com/ros-perception/image_pipeline/issues/451) seems to be promising, but it doesn't show how to set destination width and height and how to get updated camera info. 
This [link](https://github.com/ros-perception/image_pipeline/issues/297) is also similar, but I don't understand which .h file it's about and why is a header file useful. 
In the video [tutorial](http://wiki.ros.org/image_pipeline/Tutorials) I didn't find anything useful either. 
I was expecting that I can specify the destination width and height via command line and also get the updated camera info.  
Thanks in advance!

**Comment by SteveMacenski** [comment]
Please redirect this question to ROS answers.
