### ISSUE TITLE
stereocalibration crashes

### ISSUE THREAD

**Issue by BastiAB** [ros-perception/image_pipeline#46]
Hi community,
I'm trying to use the cameracalibrator.py for stereocalibration of two usb-webcams. They aren't synchronized so that I have to add an approximate time value to my command. If I dont add this value the calibration-window doesn't show up. But when I use this value I'm getting the following Error:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
rosrun camera_calibration cameracalibrator.py --pattern='acircles' --size 11x4 --square 0.035 right:=/stereo/right/image_raw left:=/stereo/left/image_raw left_camera:=/stereo/left right_camera:=/stereo/right --approximate='0.5'
Waiting for service /stereo/left/set_camera_info ...
OK
Waiting for service /stereo/right/set_camera_info ...
OK
[ERROR] [WallTime: 1381998472.508630] bad callback: <bound method Subscriber.callback of <message_filters.Subscriber instance at 0x918cbac>>
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 681, in _invoke_callback
    cb(msg)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/message_filters/__init__.py", line 72, in callback
    self.signalMessage(msg)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/message_filters/**init**.py", line 55, in signalMessage
    cb(*(msg + args))
  File "/home/faps/catkin_ws/src/image_pipeline/camera_calibration/src/camera_calibration/approxsync.py", line 70, in add
    msgs = [q[t] for q,t in zip(self.queues, vv)]
KeyError: genpy.Time[1381998472471507850]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Does anyone know where this error comes from?

**Comment by vrabaud** [comment]
I suspect this is linked to #43 (even though the error is different). You are on 32 bit right ?

**Comment by BastiAB** [comment]
Yes, I am on ubuntu 12.04 32 bit.

**Comment by vrabaud** [comment]
Hi, can you please try the fix explained in #43  ? Thx

**Comment by BastiAB** [comment]
Although the fix worked well with the other two problems (#43, #47) I have to say that it doesn't solve this problem.
It seems to me that this problem has to do with the approximate-funtion that allows to calibrate two cameras that are not synchronized.

**Comment by vrabaud** [comment]
indeed, this error seems unrelated. I don't have such a setup but I'll look into it (I think there is a rosbag online or maybe I'll ask you one).

**Comment by vrabaud** [comment]
ok, I do not get that one. Is there any way you can record a bag and send it to me ? Thx.
Please follow the mail address in the package.xml

**Comment by vrabaud** [comment]
ping, can you please record a bag and send it to me ? Thx.

**Comment by vrabaud** [comment]
that got fixed in d11edf31628c5bc4dd5511748b80b351d3e17ed6
