### ISSUE TITLE
camera calibrator for monocular camera with 320x240 resolution

### ISSUE THREAD

**Issue by Prueb32112312** [ros-perception/image_pipeline#462]
I need to use the camera_calibration package for a camera with 320x240 resolution, but I don't know where I can fix those values. I calibrated the camera with [this](http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration) package and I get:

image_width: 640
image_height: 360

What can I do?

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers
