### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by okasha55** [ros-perception/image_pipeline#464]
-- Found OpenCV: /opt/opencv3 (found suitable version "3.4.7", minimum required is "3")
.
.
.
.
.
.
make[2]: *** No rule to make target '/opt/opencv3/lib/libopencv_core.so.3.4.6', needed by 'devel/lib/image_view/disparity_view'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/disparity_view.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

i have opencv 3.4.7 , these 3.4.6 files doesn't exist and the cmake recognizes my opencv  version correctly

**Comment by SteveMacenski** [comment]
Please ask on ros answers https://answers.ros.org
