### ISSUE TITLE
port to python 3 for noetic

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/image_pipeline#466]
- [ ] camera calibration
- [ ] dynamic reconfigure across metapackage
- [ ] extract sync in image view

**Comment by sloretz** [comment]
Friendly ping. It looks like all of `image_pipeline`'s dependencies have been released to ROS Noetic, and 32 repos are waiting for it.

**Comment by SteveMacenski** [comment]
I think the blocker here is bandwidth.

**Comment by JWhitleyWork** [comment]
@sloretz This is being attempted in #507. However, it definitely needs some changes. A review of the code in that MR would be helpful.

**Comment by sloretz** [comment]
I think this could be closed thanks to #530
