### ISSUE TITLE
ROS2 Port Metaticket

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/image_pipeline#467]
* ~Ports needed with composition: #360~ COMPLETE
* update structure and files for ROS2 #468 
* update any changes in the ROS1 version not reflected during port #449 
* Replacement / augmentation for changing parameters in place of dynamic reconfigure https://discourse.ros.org/t/dynamic-reconfigure-porting/6497/14

**Comment by mikeferguson** [comment]
As far as I can see, everything that had dynamic reconfigure (and even some that didn't) has been put in a param callback - so I think we can close this as complete and deal with anything else that pops up in smaller tickets
