### ISSUE TITLE
Error using asymmetric circle pattern

### ISSUE THREAD

**Issue by BastiAB** [ros-perception/image_pipeline#47]
Hi community. After all the problems with the chessboard i tried to use an asymmetric circle pattern instead for the calibration of a single usb webcam. In most cases the pattern has been recognized and the calibration starts. But sooner or later I always get the same error: 

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
python: /build/buildd/cairo-1.10.2/src/cairo-surface.c:1287: cairo_surface_set_device_offset: Assertion `status == CAIRO_STATUS_SUCCESS' failed.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Does anyone know where this error comes from?

**Comment by vrabaud** [comment]
Hi, can you please try the fix explained in #43  ? Thx

**Comment by BastiAB** [comment]
The fix from #43 works well with this problem. I was not able to reproduce the error anymore. Nice Work.

**Comment by vrabaud** [comment]
Cool ! I'll close this one for now then :) The update will be automatic when Tully pushes the new round in a week or so.
That bug was a horrible one .... Probably some weird optimization happening in O3 32 bit on Precise ....
