### ISSUE TITLE
Request: release into melodic

### ISSUE THREAD

**Issue by furushchev** [ros-perception/image_pipeline#488]
It looks there are many changes on melodic branch since the last release.
https://github.com/ros-perception/image_pipeline/compare/50849fe041ec628ab11424cf5b5df43d533b877a...00e7c02aeb3fe4283e6327e28eb9e24f0120fd98

I'd like to kindly ask to release the new version with these updates into melodic.
Thank you very much in advance!

**Comment by JWhitleyWork** [comment]
@SteveMacenski - Are there any currently-open PRs that you'd like to see merged before I release a new Melodic version?

**Comment by SteveMacenski** [comment]
Not in my book, no

**Comment by maximus5684** [comment]
https://github.com/ros/rosdistro/pull/23503

Once this is merged it will take 2-4 weeks for the new version to be available in the repos.

**Comment by JWhitleyWork** [comment]
Wrong account.
