### ISSUE TITLE
[Camera Calibration] Exploring the stereo camera calibration result

### ISSUE THREAD

**Issue by D7823** [ros-perception/image_pipeline#497]
Hi,

So I did the camera calibration for the stereo camera and generate the yaml files for the left and right camera. But where can I find the baseline value for thees two fovs on x-axis? Or I simply measure it by myself?

Thanks in advance.

**Comment by trigal** [comment]
could be useful https://answers.ros.org/question/224342/stereo-calibration-the-extrinsic-parameters-to-tf/

**Comment by SteveMacenski** [comment]
Hi,

Thanks for your interest in this package. However, use questions should be directed to ros answers rather than in the issue trackers. 

Thanks!

S

**Comment by D7823** [comment]
Sorry about that.
