### ISSUE TITLE
hydro release 1.11.4 fails to link (at least on OS X 10.9)

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-perception/image_pipeline#50]
Hi,

so I recently started installing ROS on my new Macbook with OS X 10.9. The `stereo_iamge_proc` compilation fails with an error that a symbol from `cv_bridge` is not found. The following patch fixes compilation for me. I don't know catkin well, so I'm not sure if the dependecy should be added elsewhere.

https://gist.github.com/NikolausDemmel/7840369

Cheers

**Comment by vrabaud** [comment]
thx for reporting ! (weird it actually even compiles on Linux ...)

**Comment by NikolausDemmel** [comment]
Yeah I was woundering. Anyways, thanks for the quick fix!
