### ISSUE TITLE
Buffer overrun with message length [0] 

### ISSUE THREAD

**Issue by seanrivera** [ros-perception/image_pipeline#506]
Hello, 

I am performing a fault sensitivity analysis on several common ROS nodes and discovered that there is a buffer overrun in the image_proc node. It seems like the proc node simply works with the deserialized image after execution. 

Exception thrown when deserializing message of length [0] from [/test_node]: Buffer Overrun

**Comment by SteveMacenski** [comment]
PRs welcome!

**Comment by SteveMacenski** [comment]
Hi, 

Any update on this @seanrivera ?

**Comment by seanrivera** [comment]
Hi, 

Sorry about the delay in getting back. I haven't had time to dive into the issue for the past couple weeks.

**Comment by SteveMacenski** [comment]
@seanrivera any time to work on this? Or provide more information so someone can replicate / fix?

**Comment by mikeferguson** [comment]
No updates in years - and not enough information to actually be actionable
