### ISSUE TITLE
Installation instructions for depth_image_proc

### ISSUE THREAD

**Issue by ViacheslavRud** [ros-perception/image_pipeline#510]
Can somebody provide installation instructions?
I tried to install it with cmake + make install but still cannot run it
`rosrun nodelet load depth_image_proc/point_cloud_xyzrgb __name:=point_cloud_xyzrgb`
`[rosrun] Couldn't find executable named load below /opt/ros/kinetic/share/nodelet`

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers.
