### ISSUE TITLE
ROS2 Image Resize isn't working in image_proc

### ISSUE THREAD

**Issue by caelinsutch** [ros-perception/image_pipeline#520]
the image_resize node doesn't publish any data. The fix is removing 
```
if (pub_image_.getNumSubscribers() < 1) {
    return;
  }
``` 
in line 110 of `resize.cpp` in `image_proc`.

I'm guessing that rclcpp has a bug. I removed it for now on a custom branch, but I'm not sure if you want a pull request without this line, as it'll be publishing unnecessary data. Let me know what you think.

**Comment by SteveMacenski** [comment]
Try with this API: http://docs.ros2.org/eloquent/api/rclcpp/classrclcpp_1_1Node.html#a7aa2ed22450d2f3300ea5b879acd73b8

That's what I've used in the past, I think you're right that the PublisherBase's has an issue (or component issues). I'm seeing that line commented out in a few (not all) of the components in image proc. If you're going to remove it, please simply comment it out, do not delete the line. We will need to revisit this at some point. 

If you submit a PR, please comment out all instances of that in image proc, I count just a few.
