### ISSUE TITLE
Melodic on odroid-n2/ubuntu 18.04 cannot find ImageViewConfig.h

### ISSUE THREAD

**Issue by bltDefender** [ros-perception/image_pipeline#525]
```
30%] Building CXX object abot-kinetic/image_pipeline/image_view/CMakeFiles/image_view.dir/src/nodelets/image_nodelet.cpp.o

Scanning dependencies of target image_rotate_gencfg
/root/catkin_ws/src/abot-kinetic/image_pipeline/image_view/src/nodelets/image_nodelet.cpp:34:10: fatal error: image_view/ImageViewConfig.h: No such file or directory
 #include <image_view/ImageViewConfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
abot-kinetic/image_pipeline/image_view/CMakeFiles/image_view.dir/build.make:62: recipe for target 'abot-kinetic/image_pipeline/image_view/CMakeFiles/image_view.dir/src/nodelets/image_nodelet.cpp.o' failed
make[2]: *** [abot-kinetic/image_pipeline/image_view/CMakeFiles/image_view.dir/src/nodelets/image_nodelet.cpp.o] Error 1
CMakeFiles/Makefile2:3205: recipe for target 'abot-kinetic/image_pipeline/image_view/CMakeFiles/image_view.dir/all' failed
make[1]: *** [abot-kinetic/image_pipeline/image_view/CMakeFiles/image_view.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Can you please give me a hint what am I missing here? Where do I get the missing header file from?

**Comment by JWhitleyWork** [comment]
@bltDefender This header file is generated by `dynamic_reconfigure` from the `image_view/cfg/ImageView.cfg` file when the node is built. Make sure you have installed all prerequisites using `rosdep` before trying to build the node and `catkin clean` your workspace and try again.

**Comment by bltDefender** [comment]
I did already. All deps satisfied, ws was cleaned. From the build log I cannot see that `dynamic_reconfigure` writes that header file while others are written.

**Comment by JWhitleyWork** [comment]
Can you give me more context? What command are you using to build the workspace? How is your workspace laid out? What version or commit hash of the repository and from which branch are you using?

**Comment by bltDefender** [comment]
To ease the debugging I created a new workspace. In src I cloned recent branch `origin/melodic`. Above src folder I do resolve deps via `rosdep install --from-paths src -y --ignore-src --rosdistro=melodic`. Then I simply run `catkin_make`which fails . See https://pastebin.fun/6hamphEvyb

Ros Version is 1.14.5. Ubuntu ist bionic 18.04.4. Ros packages come from http://packages.ros.org/ros/ubuntu bionic main

**Comment by bltDefender** [comment]
Is there anything wrong the way I did it?

**Comment by JWhitleyWork** [comment]
@bltDefender If you are using packages from the apt repository then you would not have this issue because they would already be pre-built binaries. You are building a workspace which includes the source code of this repository. I need to know which version (tag or commit hash) of the source code you are building.

**Comment by mikeferguson** [comment]
18.04 is now EOL
