### ISSUE TITLE
Mind making another Noetic release of image_pipeline?

### ISSUE THREAD

**Issue by sloretz** [ros-perception/image_pipeline#535]
Mind making another Noetic release with #531? It looks like the `image_view` armhf binary job failed due to the race with generating `ImageViewConfig.h`. I can re-trigger the job and hope we avoid the race this time; but another Noetic release would guarantee it.

http://build.ros.org/view/Nbin_ufhf_uFhf/job/Nbin_ufhf_uFhf__image_view__ubuntu_focal_armhf__binary/5/console

**Comment by JWhitleyWork** [comment]
GTG. https://github.com/ros/rosdistro/pull/24950
