### ISSUE TITLE
video_recorder is making an empty avi file

### ISSUE THREAD

**Issue by blaine141** [ros-perception/image_pipeline#559]
I am trying to take the contents of a bag file and record them to a video file using the following launch file. The result is always an output.avi file that is 4.1kB and is not able to be played. Any advice?
[record_video.txt](https://github.com/ros-perception/image_pipeline/files/4882924/record_video.txt)

**Comment by SteveMacenski** [comment]
Please ask on ROS answers

**Comment by blaine141** [comment]
If anyone else is having this issue it is caused by the image topic not having a timestamp
