### ISSUE TITLE
Disable "Publish Color!" debug_info

### ISSUE THREAD

**Issue by dawonn-haval** [ros-perception/image_pipeline#568]
https://github.com/ros-perception/image_pipeline/blob/c831f7c6f4ce0864de27306d19d3d2c888d5ca73/image_proc/src/debayer.cpp#L181

I think this might be a left-over debug print, bloats log files unnecessarily.

**Comment by JWhitleyWork** [comment]
@dawonn-haval Would you mind submitting a PR to remove it? Given that it is for ROS2, we'd appreciate one against the `dashing` branch and another against the `ros2` (`foxy`) branch.

**Comment by JWhitleyWork** [comment]
Closed by #577 and #578.
