### ISSUE TITLE
depth_image_proc: Possible missing build depend on libpcl-dev

### ISSUE THREAD

**Issue by cottsay** [ros-perception/image_pipeline#57]
This will likely not be limited to only depth_image_proc.

When building RPMs, mock employs a more robust dependency checking system than is currently used to build the ROS debs. It has discovered that it is possible to install pcl_ros without libpcl-dev (which isn't wrong). However, projects that utilize pcl_ros for building MUST also have the PCL header files provided by libpcl-dev.

The most efficient solution dependency-wise is to make packages with build dependencies on pcl_ros to also build depend on libpcl-dev.

At current, package.xml's don't seem to have the ability to declare additional downstream build dependencies (while catkin does in cmake).

This is the only package I've discovered _so far_, but I haven't been able to build quite a few other possible pcl deps, so I'll know more soon.

PCL maintainers: @wjwwood @jkammerl

**Comment by wjwwood** [comment]
`pcl_ros` should have a `run_depend` on `libpcl-dev`, that should solve the problem.

**Comment by cottsay** [comment]
I agree that it will solve the problem. I'll open a pull against perception_pcl then.

**Comment by wjwwood** [comment]
Thanks.

**Comment by cottsay** [comment]
Closed via https://github.com/ros-perception/perception_pcl/issues/43
