### ISSUE TITLE
Disparity Nodelet bug (?)

### ISSUE THREAD

**Issue by AmmarkoV** [ros-perception/image_pipeline#58]
Disparity Nodelet conversion code is erroneous since it does

Disparity = fx (  -baseline / fx ) \* 0.001 / Depth which is actually 
Disparity = -baseline \* 0.001 / Depth 
this should be 
Disparity = fx \* ( -baseline ) \* 0.001 / Depth

Fix Is : 
  disp_msg->T = -info_msg->P[3] / fx; 
  should be
  disp_msg->T = -info_msg->P[3];

https://github.com/ros-perception/image_pipeline/blob/hydro-devel/depth_image_proc/src/nodelets/disparity.cpp#L136

**Comment by ahendrix** [comment]
I think this particular piece of code has been in use for many years, so I'd be hesitant to change it.

Can you explain exactly WHY it's wrong, and where it's causing an error for you?

**Comment by AmmarkoV** [comment]
It is wrong because  the way to convert depth ( in mm or meters or w/e ) to disparities is as seen here ( for example http://code.google.com/p/sentience/wiki/StereoRanging  , or from a ROS resource http://wiki.ros.org/kinect_calibration/technical  z = b*f / d,  ) 

float focal_length_pixels = focal_length_mm \* sensor_pixels_per_mm;
            float distance_mm = baseline_mm \* focal_length_pixels / disparity_pixels; 
 AND to go from distance to disparity
            float disparity_pixels  = baseline_mm \* focal_length_pixels / distance_mm; 

what is actually done  by the code as i shown is not this equation but rather 
Disparity = fx ( -baseline / fx ) \* 0.001 / Depth which is actually (since fx/fx = 1)
Disparity = -baseline\* 0.001 / Depth  and that is  wrong 

Please note that the original disparity function should be this ( https://github.com/ros-drivers/openni_camera/blob/hydro-devel/src/openni_depth_image.cpp#L163 , in OpenNI1 before this code got split on to nodelets ) and notice how it has changed..

**Comment by AmmarkoV** [comment]
Also from what i can see there is only one commit on this file at  2012-03-12  mihelich when it got moved to depth_image_proc , in any case I am pretty sure that the conversion is wrong..

**Comment by ahendrix** [comment]
I think this the existing implementation is correct.

In particular, the [CameraInfo](http://docs.ros.org/api/sensor_msgs/html/msg/CameraInfo.html).P[3] is Tx, which is defined as Tx = -fx' \* B ( -focal_length \* baseline).

The [DisparityImage](http://docs.ros.org/api/stereo_msgs/html/msg/DisparityImage.html).T is defined as the baseline, so:
T = -( -fx \* baseline ) / fx
which is equivalent to:
T = baseline

If this is actually causing problems for you, it may be that the Tx value in the CameraInfo is not being set properly.

**Comment by vrabaud** [comment]
@AmmarkoV  , any rebuttal concerning @ahendrix  's remark ?

**Comment by AmmarkoV** [comment]
Yes , well actually , when some one says T ( in the literature ) he means
Translation Vector ( for example in OpenCV
http://docs.opencv.org/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html)
In any case if i supply Baseline \* fX  as the T or P[3] value I do get the
value range expected.

Also at the documentation of
http://docs.ros.org/api/sensor_msgs/html/msg/CameraInfo.html , as Austin
said , it reads  Tx = -fx' \* B, where B is the baseline between the
cameras. so  the code is consistent with the documentation and I am at
the wrong ..

In any case from a common-sense viewpoint it is weird since we already give
the Fx value ( P[0] )  we should only give the Baseline (for  P[3] ) and do
the multiplication only one time inside the nodelet..
(  I don't see a conceptual reason for the current state of things ) . Also
since everything is based on this notation , I understand it is impossible
to change this without breaking all the nodes that use the disparity
nodelet..

In any case thanks for the immediate responses
Keep up the good work guys.. :)

And this is issue should be closed

2014-03-02 14:04 GMT+02:00 Vincent Rabaud notifications@github.com:

> @AmmarkoV https://github.com/AmmarkoV , any rebuttal concerning
> @ahendrix https://github.com/ahendrix 's remark ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-perception/image_pipeline/issues/58#issuecomment-36452436
> .

## 

Ammar Qammaz
http://ammar.gr

**Comment by vrabaud** [comment]
right, I get the confusion. Thx for digging in !
