### ISSUE TITLE
 MODE_SGBM_3WAY in opencv

### ISSUE THREAD

**Issue by copaah** [ros-perception/image_pipeline#582]
I am having a hard time understanding how to set the stereo mode in SGBM. 

[The opencv documentation](https://docs.opencv.org/3.4/d2/d85/classcv_1_1StereoSGBM.html) mentions four different modes. is there support for all four in `stereo_image_proc` and if so, how to set the mode to `MODE_SGBM_3WAY`?

**Comment by mikeferguson** [comment]
It appears this is not currently supported - PRs welcome for adding ROS parameters to set the mode
