### ISSUE TITLE
Impossible to change the name in monocular calibration

### ISSUE THREAD

**Issue by rlalleme** [ros-perception/image_pipeline#59]
The output of the monocular camera's calibration contains the line:

[narrow_stereo/left]

It should either be a parameter (given when starting the calibration) or a value like "camera" since it is **not** a stereo.

The problem stands here:
image_pipeline/camera_calibration/src/camera_calibration/calibrator.py:478:        + "[narrow_stereo/%s]" % name + "\n"

**Comment by ahendrix** [comment]
Link to offending line: https://github.com/ros-perception/image_pipeline/blob/hydro-devel/camera_calibration/src/camera_calibration/calibrator.py#L478

Yeah; that should probably be just `"[%s]\n" % name` or something like that....

I wonder if this shows up in the stereo calibration as well?

**Comment by vrabaud** [comment]
stereo has [narrow_stereo/left] and [narrow_stereo/right]
Working on a patch.

**Comment by vrabaud** [comment]
please review the patch (it's pretty trivial and it maintains bc)

**Comment by rlalleme** [comment]
I do not know Python so I can not really review the patch but should the name have a new option ?

[image_pipeline / camera_calibration / nodes / cameracalibrator.py:326 and bellow](https://github.com/ros-perception/image_pipeline/blob/hydro-devel/camera_calibration/nodes/cameracalibrator.py#L326)

**Comment by vrabaud** [comment]
right, that was only for the classes. I pushed the full fix in master.

**Comment by trainman419** [comment]
That looks like a reasonable set of changes to me.
:+1:
