### ISSUE TITLE
Eloquent Branch Request

### ISSUE THREAD

**Issue by allenh1** [ros-perception/image_pipeline#590]
When building, I get the following on Eloquent:

```
ros-perception/image_pipeline/image_proc/include/image_proc/rectify.hpp:37:10: fatal error: image_transport/image_transport.hpp: No such file or directory
 #include <image_transport/image_transport.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I believe this happens because the `.hpp` version of the file does not exist on the Eloquent branch (though I'm aware it does in Foxy).

Could we please create an eloquent branch with the `.h` version?

**Comment by allenh1** [comment]
I made one on my fork in the meantime: https://github.com/allenh1/image_pipeline/tree/eloquent

**Comment by JWhitleyWork** [comment]
@allenh1 Have you tried the `dashing` branch instead? It is more likely to be compatible with Eloquent.

**Comment by Schloern93** [comment]
Hallo @allenh1 
I also use ros eloquent and try to build the image processing. I have used your provided branch for this. 
But i run in the following error:

> stderr: image_proc                             
/home/florian/test_imgage_proc/ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp: In instantiation of ‘void image_proc::debayer2x2toBGR(const cv::Mat&, cv::Mat&, int, int, int, int) [with T = unsigned char]’:
/home/florian/test_imgage_proc/ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp:216:71:   required from here
/home/florian/test_imgage_proc/ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp:53:3: error: ‘type’ is not a member of ‘cv::DataType<cv::Vec<unsigned char, 3> >’
   dst.create(src.rows / 2, src.cols / 2, cv::DataType<DstPixel>::type);
   ^~~
/home/florian/test_imgage_proc/ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp: In instantiation of ‘void image_proc::debayer2x2toBGR(const cv::Mat&, cv::Mat&, int, int, int, int) [with T = short unsigned int]’:
/home/florian/test_imgage_proc/ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp:224:72:   required from here
/home/florian/test_imgage_proc/ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp:53:3: error: ‘type’ is not a member of ‘cv::DataType<cv::Vec<short unsigned int, 3> >’
make[2]: *** [CMakeFiles/crop_decimate.dir/src/crop_decimate.cpp.o] Error 1
make[1]: *** [CMakeFiles/crop_decimate.dir/all] Error 2
make: *** [all] Error 2
Failed   <<< image_proc [1.83s, exited with code 2]

I solved this by adding this line to ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp
#define OPENCV_TRAITS_ENABLE_DEPRECATED  to allow old type traits for open cv

If I start the launch file "point_cloud_xyz.launch.py" for example.
I get the following error:

>  [INFO] [launch]: All log files can be found below /home/florian/.ros/log/2021-01-09-13-55-17-192620-florian-desktop-30350
    [INFO] [launch]: Default logging verbosity is set to INFO
    [ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: init() got an unexpected keyword argument 'plugin'

The error is the same for all launch files in the "depth_image_proc" package.
Do you have a solution for this? 
Many thanks in advance for the help.

**Comment by allenh1** [comment]
> I solved this by adding this line to ros2_ws/src/image_pipeline/image_proc/src/crop_decimate.cpp
#define OPENCV_TRAITS_ENABLE_DEPRECATED to allow old type traits for open cv

Interesting, I was seeing this issue on one of my computers recently. I'll push that fix to my fork -- thanks for the note!

> [py]: init() got an unexpected keyword argument 'plugin'

Ah, this is something I neglected to backport. In ROS 2 Foxy and later, the API changed. See [here](https://github.com/ros2/launch_ros/blob/07497cd1f6576b7d3aff79a490016d583f9f3dcb/launch_ros/launch_ros/descriptions/composable_node.py#L38) for the correct naming. I'll update this at some point in the near future.

**Comment by Schloern93** [comment]
Thanks this worked for me.
I have adjusted my launch file as follows.

```
# launch plugin through rclcpp_components container
        launch_ros.actions.ComposableNodeContainer(
            node_name='container',
            node_namespace='',
            package='rclcpp_components',
            node_executable='component_container',
            composable_node_descriptions=[
                # Driver itself
                launch_ros.descriptions.ComposableNode(
                    package='depth_image_proc',
                    node_plugin='depth_image_proc::PointCloudXyzNode',
                    node_name='point_cloud_xyz_node',
                    remappings=[('image_raw', '/D435/depth/image_rect_raw'),
                                ('camera_info', '/D435/depth/camera_info'),
                                ('image', '/camera/depth/converted_image')]
                ),
            ],
            output='screen',
        ),
```

I am now using the depth_image_proc package to publish a sorted PointCloud2 message. 
If I look at the documentation(2.3) linked below I need two topics which I have to pass.
http://wiki.ros.org/depth_image_proc?distro=noetic
But in the launch file there are three topics to pass. 

My question is which topic is needed in this line?
`('image', '/camera/depth/converted_image')]`

Thanks for the help.
