### ISSUE TITLE
camera calibration no display

### ISSUE THREAD

**Issue by yelbuod** [ros-perception/image_pipeline#591]
when i enter `rosrun camera_calibration cameracalibrator.py –size 8×6 –square 0.03 image:=/usb_cam/image_raw` in the command line, i encounter such situation. my display get black and seens no complete as follows:
![Screenshot from 2020-08-23 14-29-52](https://user-images.githubusercontent.com/52616354/90974825-57738b80-e561-11ea-9b8f-a2d913714c49.png)
and my terminal tell me as follows:
![Screenshot from 2020-08-23 16-45-31](https://user-images.githubusercontent.com/52616354/90974830-73772d00-e561-11ea-917d-4e47c2ac368f.png)
my environment is ubuntu 18.04, ros melodic. Thank you.

**Comment by Mingg8** [comment]
We have same problem. Is there any solution?

**Comment by JWhitleyWork** [comment]
@MINUS-1ONE What version of `camera_calibration` are you using? Did you install it from source or with `apt`?

**Comment by yelbuod** [comment]
> @MINUS-1ONE What version of `camera_calibration` are you using? Did you install it from source or with `apt`?

I install from source code of this project and catkin_make.

**Comment by yelbuod** [comment]
> We have same problem. Is there any solution?

I solve this by using calibration in autoware which is called autoware_camera_lidar_calibrator.

**Comment by Mingg8** [comment]
I solved it by using old version.
It was on kinetic branch and commit on May, 2018

2020년 8월 28일 (금) 오후 4:50, MINUS-1ONE <notifications@github.com>님이 작성:

**Comment by tentenNT** [comment]
I think you're building a noetic branch.
Building the source code for the melodic branch should fix it.

**Comment by Fellowflyingsky** [comment]
![Screenshot from 2022-03-01 07-58-49](https://user-images.githubusercontent.com/71952790/156173536-7042875d-77a9-4cfc-8640-eae2771b93bf.png)
1.use  the opencv4.1.1 for python
2.line 725 in calibrator.py changed to Calibrator.__init__(self,*args, **kwargs).

**Comment by mikeferguson** [comment]
Looks like this might have been a branch mismatch - but regardless, several years old
