### ISSUE TITLE
distortion are zero

### ISSUE THREAD

**Issue by dnmagi5** [ros-perception/image_pipeline#598]
If enter rosrun camera_calibration cameracalibrator.py –size 8×6 –square 0.03 image:=/usb_cam/image_raw **--k 3** in the command line, i can get below camera matrix
camera matrix
1451.846342 0.000000 343.137572
0.000000 1451.846342 237.224924
0.000000 0.000000 1.000000

distortion
-0.160041 1.349563 -0.001729 -0.000031 -9.472244

If enter rosrun camera_calibration cameracalibrator.py –size 8×6 –square 0.03 image:=/usb_cam/image_raw **--k 6** in the command line, the distortion of camera matrix will be all zero
camera matrix
1453.092336 0.000000 343.505652
0.000000 1453.092336 237.156484
0.000000 0.000000 1.000000

distortion
0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000

my environment is ubuntu 16.04, ros kinetic
Thank you

**Comment by mikeferguson** [comment]
Kinetic is now EOL
