### ISSUE TITLE
How to save images with timestamp using C++ 

### ISSUE THREAD

**Issue by LArayane** [ros-perception/image_pipeline#610]
Hello,

I am trying to save images with their timestamp. I used Image saver tool in [here](http://wiki.ros.org/image_view) but the saved images has no timestamp. Also I saw  [this solution](https://github.com/ros-perception/image_pipeline/pull/203) but it terns out that it was for video recording.

Is there any solution for this in C++!!

Thanks in advance

**Comment by Gorschel** [comment]
this is not an issue, it is a question -> go to [Stackoverflow](https://stackoverflow.com/)
Issue can be closed.

**Comment by mikeferguson** [comment]
Please use https://robotics.stackexchange.com for questions
