### ISSUE TITLE
ros-noetic python interpretor has no 'python'

### ISSUE THREAD

**Issue by paszoujp** [ros-perception/image_pipeline#612]
I installed camera_calibration from apt-get
when I run cameracalibrator.py, this error occurs:
_/opt/ros/noetic/bin/rosrun: /opt/ros/noetic/lib/camera_calibration/cameracalibrator.py: /usr/bin/python: bad interpreter: No such file or directory
/opt/ros/noetic/bin/rosrun: line 150: /opt/ros/noetic/lib/camera_calibration/cameracalibrator.py: Success_

I then looked in /usr/bin/, then find that there's no file named python, only python2 or python3 something
I then edited cameracalibrator.py, changed the 1st line from `#!/usr/bin/python` to  `#!/usr/bin/python3`,then problem solved
Maybe you should update the python interpreter statement in each python file, for ubuntu 20.04 and ros noetic?

**Comment by JWhitleyWork** [comment]
This should be fixed after 0a85550b361575478bf5ebf622d2f90d0a097795. Please pull the latest `noetic` branch and test with a source-build.

**Comment by JWhitleyWork** [comment]
Closing due to lack of feedback.
