### ISSUE TITLE
Topic /points cant show in rviz

### ISSUE THREAD

**Issue by Schloern93** [ros-perception/image_pipeline#625]
Hallo,

this is probably a rviz specific question.
I use the package "depth_image_proc/point_cloud_xyz".
With ros2 topic echo I can view my PointCloud2 message (Topic: "/points"). 
When I try to display the PointCloud2 message in rviz, rviz does not show any points. 
But the topic /points is found and I can view it with ros2 topic echo /points.

Thats the frame_id which is set to my PointCloud2 msgs

> frame_id: camera_depth_optical_frame

I select this frame_id in rviz as fixed_frame.

Thanks for the help.

**Comment by Schloern93** [comment]
I solved it by changing this line in the "depth_image_proc/src/point_cloud_xyz":
`pub_point_cloud_ = create_publisher<PointCloud2>("points", rclcpp::SensorDataQoS());`
to
`pub_point_cloud_ = create_publisher<PointCloud2>("points", 1);`

Can someone explain to me the reason for this?

**Comment by swiz23** [comment]
I am running into the same issue as well (though I didn't try to modify the code) specifically in foxy. Haven't tried it in galactic.

**Comment by JWhitleyWork** [comment]
Once you subscribe to the topic in `rviz2`, you can expand the topic details and change the QoS settings to match the `SensorDataQoS` settings. Here they are: https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SensorDataQoS.html. If this works for you, please let me know and I will close this issue.

**Comment by swiz23** [comment]
Thanks @JWhitleyWork, that did the trick!!

I specifically had to change the PointCloud2 -> Topic -> Reliability Policy in Rviz2 from 'Reliable' to 'Best Effort' for the pointcloud to show.

**Comment by JWhitleyWork** [comment]
Excellent! Closing.
