### ISSUE TITLE
[ROS2] Frame match in point_cloud_xyzrgb.cpp

### ISSUE THREAD

**Issue by fmrico** [ros-perception/image_pipeline#628]
Hi all,

Is it really necessary that the RGB image and the depth image match here?

https://github.com/ros-perception/image_pipeline/blob/683d980f4682305aeef05f67ecb3b16c8b232a04/depth_image_proc/src/point_cloud_xyzrgb.cpp#L168

The Astra driver, for example, publishes both images in different frames, but coincident frames. If I remove this condition, it works like a charm.

![Captura de pantalla 2021-01-30 09:21:21](https://user-images.githubusercontent.com/3810011/106351656-ba6e0900-62dd-11eb-82f4-7ca0196d615b.png)

Maybe the fix could be to check if these frames coincide...

Best
Francisco

**Comment by mikeferguson** [comment]
Looks like fix was merged
