### ISSUE TITLE
ERROR: Image received from camera is incomplete

### ISSUE THREAD

**Issue by Cristian-wp** [ros-perception/image_pipeline#636]
Hi!
I am using a Flir Blackfy S to record a video using video_recorder.
I launch the node during boot in order to start recording a video .mp4 and a rosbag immediately, but after 1/2 minutes I have this error:

```
spinnaker-start[843]: [ INFO] [[ERROR] [1612878222.719928123]: [SpinnakerCamera::grabImage] Image received from camera ID is incomplete.

spinnaker-start[843]: [ERROR] [1612878222.720138675]: Failed to disconnect with error: [SpinnakerCamera::disconnect] Failed to disconnect camera 

```
After this error the recording stops and save the file .mp4, but the rosbag is not affected of this error.

I think that I can solve this using even the corrupted images, there is and option to do this in video_recorder?
Can you please help me to solve this problem?

**Comment by mikeferguson** [comment]
This appears to be an issue with particular hardware/config (and corrupted images/messages) - really better suited to https://robotics.stackexchange.com
