### ISSUE TITLE
catkin_make error 

### ISSUE THREAD

**Issue by paul3333** [ros-perception/image_pipeline#638]
I am running ubuntu 14 with ROS Indigo and face a compiling error using catkin_make.

I receive the following error:
`CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_workspace.cmake:95 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:63 (catkin_workspace)

-- Configuring incomplete, errors occurred!
See also "/home/paul/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/paul/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
paul@paul-E7450:~/catkin_ws$ 
`
When doing "catkin_make_isolated" other errors appear.

Has anyone faced this issue? How were you installing this package?  Any help would be highly appreciated.

**Comment by JWhitleyWork** [comment]
I'm sorry but Indigo is no longer a supported version of ROS - it went end-of-life in April, 2019. However, try installing from the repository instead if you haven't already.
