### ISSUE TITLE
False Depth Image from depth_image_pro/register

### ISSUE THREAD

**Issue by Marki2112** [ros-perception/image_pipeline#643]
Hello everyone,

i using the realsense d435 and ROS Melodic to transform the depth image from "camera_depth_optical_link" to the "camera_color_optical_link". I am using a rosbag to get the data, but the result look like for the transformed depth image not correct. I install it from the source and have the version 1.15.0-1bionic.20210112.195548. My current launch-file can you see here:
`<launch>
    
    <arg name="color_camera_info" default="/camera/color/camera_info"/>
    <arg name="depth_camera_info" default="/camera/depth/camera_info"/>
    <arg name="depth_image" default="/camera/depth/image_rect_raw"/>
    
    <node pkg="nodelet" type="nodelet" name="nodelet_manager" args="manager"/>

    <node pkg="nodelet" type="nodelet" name="depth2rgbFrame"
          args="load depth_image_proc/register nodelet_manager">
      
      
      <remap from="rgb/camera_info" to="$(arg color_camera_info)"/>
      <remap from="depth/camera_info" to="$(arg depth_camera_info)"/>
      <remap from="depth/image_rect" to="$(arg depth_image)"/>

    </node>
</launch>`
Also i tested it with realdata but the isssue was there too. Here you can see the difference between the normal depth image  and the transformed depth image:
normal depth image 
![image_depth](https://user-images.githubusercontent.com/64910738/111804026-f5e58680-88cf-11eb-8b0a-bc102fcc5e53.png)
transformed depth image 
![depth2RGB](https://user-images.githubusercontent.com/64910738/111804024-f54cf000-88cf-11eb-9df2-bf855431f932.png)

Why the transformed depth image look likes different ?

**Comment by lucasw** [comment]
Try setting `fill_upsampling_holes` to true.

**Comment by mikeferguson** [comment]
There is a suggested fix, and this sort of thing should probably go to https://robotics.stackexchange.com in the future
