### ISSUE TITLE
catkin_make build image_proc repo error

### ISSUE THREAD

**Issue by john-le1996** [ros-perception/image_pipeline#647]
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  image_pipeline/image_view/CMakeLists.txt:42 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/asd/image_pipelin/build/CMakeFiles/CMakeOutput.log".
See also "/home/asd/image_pipelin/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

ros kinetic
ubuntu 16.04

**Comment by JWhitleyWork** [comment]
@john-le1996 Please provide the following:

- Which branch or commit are you using?
- What command are you using to build your workspace?

It looks like your workspace is not set up correctly. Your folders should look like this:

- my_workspace/
  - build/
  - devel/
  - src/
    - image_pipeline/

And you should run the `catkin` commands inside `my_workspace/`.

**Comment by john-le1996** [comment]
thanks for response
my workspace is okay sir but building having an error
i use this http://wiki.ros.org/image_proc
kinetic git clone  git https://github.com/ros-perception/image_pipeline.git

**Comment by john-le1996** [comment]
Make Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  image_pipeline/image_view/CMakeLists.txt:42 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/asd/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/asd/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by mikeferguson** [comment]
CI is passing on all supported distros - so this is likely an issue with your machine. If the issue persists, I suggest posting to https://robotics.stackexchange.com
