### ISSUE TITLE
New release into ROS 2 Rolling

### ISSUE THREAD

**Issue by clalancette** [ros-perception/image_pipeline#648]
Hello image_pipeline maintainers!

It would be great to #644 reviewed and merged, and then to have a new image_pipeline source and bloom release done into Rolling.  This should make some of the recent fixes available in both source and binary.

If the maintainers don't have time for this, the ROS 2 core team can do a release to get things moving.  Please let us know one way or another, thanks!

**Comment by JWhitleyWork** [comment]
Several releases for `rolling` have happened since this. Closing.
