### ISSUE TITLE
incorrect framerate with video_recorder

### ISSUE THREAD

**Issue by jarvisschultz** [ros-perception/image_pipeline#65]
Most of the cameras/camera drivers I have around (Asus Xtion, Kinect, webcams) tend to publish the `camera_info` each time the the `image` topic is published. This means that the `callback` on line 35 gets called at twice the framerate of the image topic we are trying to record. This results in videos that playback at 1/2 the real-world speed if the user inputs an `~fps` param equal to the `image` topic publish frequency (which is the logical choice IMO).

I haven't used `image_pipeline` a ton, and I haven't used many camera drivers, so I don't know if publishing the `camera_info` every time is common. But for drivers that do this, here is what fixed the issue for me (lines 57-60):

```
    ROS_INFO_STREAM("Starting to record " << codec << " video at " << size << "@" << fps << "fps. Press Ctrl+C to stop recording." );

    }
    else if (outputVideo.isOpened() && info) return;
```

**Comment by vrabaud** [comment]
thx !
