### ISSUE TITLE
New release for ROS noetic

### ISSUE THREAD

**Issue by Tobias-Fischer** [ros-perception/image_pipeline#650]
We just noticed that camera-calibration is broken in RoboStack (https://github.com/RoboStack/ros-noetic). This was already fixed in https://github.com/ros-perception/image_pipeline/commit/0a85550b361575478bf5ebf622d2f90d0a097795 but as there was no release yet, it is still broken. It would be great if you could release a new version.

/cc @steveQUT @wolfv @traversaro

**Comment by mikeferguson** [comment]
1.17.0 was released Oct 17, 2022 - which is after this ticket was filed
