### ISSUE TITLE
Camera calibration. Which service should I call?

### ISSUE THREAD

**Issue by RodrigoFBernardo** [ros-perception/image_pipeline#657]
Hi

I'm trying to calibrate a camera, only I don't have the service (set_camera_info).

/camera/color/image_raw/compressed/set_parameters
/camera/color/image_raw/compressedDepth/set_parameters
/camera/color/image_raw/theora/set_parameters
/camera/color/image_rect_color/compressed/set_parameters
/camera/color/image_rect_color/compressedDepth/set_parameters
/camera/color/image_rect_color/theora/set_parameters
/camera/color_rectify_color/get_loggers
/camera/color_rectify_color/set_logger_level
/camera/color_rectify_color/set_parameters

 rosrun camera_calibration camacalibrator.py --size 8x6 --square 0.028 image:=/camera/color/image_raw set_camera_info:= ...???

What could I be missing?

**Comment by clydemcqueen** [comment]
Append `--no-service-check` to the end of the command line.

See http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration for more info.
