### ISSUE TITLE
Video Recorder - g_last_wrote_time has inconsistent clock_type

### ISSUE THREAD

**Issue by larsll** [ros-perception/image_pipeline#673]
When running the image_view video_recorder in foxy I get the following error message:

```
[video_recorder-2] terminate called after throwing an instance of 'std::runtime_error'
[video_recorder-2]   what():  can't subtract times with different time sources [1 != 2]
```

This is related to `image_view/src/video_recorder_node.cpp` where the variable `g_last_wrote_time` seems to be inconsistently defined. Forcing it to be of type `RCL_SYSTEM_TIME` resolves the issue.

Setup based on https://jeffzzq.medium.com/ros2-image-pipeline-tutorial-3b18903e7329

See also drafted pull request.

**Comment by mikeferguson** [comment]
Should be fixed by #675
