### ISSUE TITLE
Compiling with catkin_make and opencv4.2 fails with error: ‘StereoBM’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by redchillipadi** [ros-perception/image_pipeline#685]
I am compiling image_pipeline using catkin_make on Ubuntu Focal Fossa on the raspberry pi. It has python3-opencv/focal,now 4.2.0+dfsg-5 arm64 installed, and I am using ros-noetic-desktop-full

Compilation fails with:
In file included from /home/ubuntu/catkin_ws/src/image_pipeline/stereo_image_proc/src/libstereo_image_proc/processor.cpp:35:
/home/ubuntu/catkin_ws/src/image_pipeline/stereo_image_proc/include/stereo_image_proc/processor.h:172:23: error: ‘StereoBM’ is not a member of ‘cv’
  172 |   mutable cv::Ptr<cv::StereoBM> block_matcher_; // contains scratch buffers for block matching
      |                       ^~~~~~~~

I was able to fix this by adding
#include <opencv2/calib3d.hpp>
to processor.h

**Comment by mikeferguson** [comment]
The appropriate header appears in the noetic branch - so this should be fixed
