### ISSUE TITLE
Is there any tutorial/README on how to use the ChArUco board calibration

### ISSUE THREAD

**Issue by sisaha9** [ros-perception/image_pipeline#689]
I am currently using ROS Noetic. I was using the command introduced in #548 to try out ChArUco board calibration. However I could not get the board detection to work. Does it still follow similar instructions to http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration after the rosrun command or are there any other differences that should be noted

**Comment by Choco83** [comment]
take a look here
https://github.com/ros-perception/image_pipeline/pull/548
