### ISSUE TITLE
is registartion required ?>

### ISSUE THREAD

**Issue by vishalleo1** [ros-perception/image_pipeline#701]
if the color/rgb image resolution and depth image resolution is same and we get the images from the same camera, then we need to do the registration process?

**Comment by JWhitleyWork** [comment]
Unless you have a multi-spectral camera (which costs tens of thousands of dollars) then you aren't getting the depth and RGB images from the same "camera" (i.e. same image sensor) which means registration is required.

**Comment by mikeferguson** [comment]
Appears answered - if you're looking for more detail, I suggest posting to https://robotics.stackexchange.com
