### ISSUE TITLE
Ros2 Foxy resize node, cannot find published camera_info

### ISSUE THREAD

**Issue by lancevoly** [ros-perception/image_pipeline#703]
I am using the resize node in ros2 foxy, which subscribes from a camera_info topic and republishes it with updated camera_info. 
I wonder how I can subscribe to the updated camera_info, which is denoted as ~camera_info in the ros wiki. I tried node_name/camera_info, but it doesn't work. 

Thanks for the help!

**Comment by clydemcqueen** [comment]
In my tests ResizeNode subscribes and publishes to the same camera info topic, so the original and modified CameraInfo messages are mixed. This basically makes ResizeNode unusable.

I think this is the root cause: https://github.com/ros-perception/image_common/issues/187

**Comment by mikeferguson** [comment]
Appears that #693 is the workaround for this, there are other tickets following image_transport issues.

**Comment by jiduowang** [comment]
Hey, have you solve this problem? Now I have the same question. I have two camera and I want to publish different info of camera
