### ISSUE TITLE
ros2: variables undefined

### ISSUE THREAD

**Issue by azhural** [ros-perception/image_pipeline#713]
51a60e723c331507c05e3be37734884cf79ebff9 has introduced a `fisheye_flags` variable in camera_calibration's camera_calibrator.py L108, which is undefined. L153 reads `self.checkerboard_flags`, but should read `self._checkerboard_flags`.

After fixing that locally I ran into a `boards` undefined error. I'm unsure if that's user error.

**Comment by mikeferguson** [comment]
The _checkerboard_flags part is fixed - but not the boards issue

**Comment by mikeferguson** [comment]
Assigning to myself - going to run through the various calibration issues in the next two weeks

**Comment by mikeferguson** [comment]
This appears to be correct in code at this point - can't really determine what the "boards error" was
