### ISSUE TITLE
Difference between image_raw and image_color outputs.

### ISSUE THREAD

**Issue by gustavojoseleite** [ros-perception/image_pipeline#727]
The documentation say:
image_raw - Raw image stream from the camera driver. 
image_color - Color unrectified image. 
So if image_color is unrectified, what is the exactly difference between image_raw and image_color? When i should be use image_color rather than image_raw?

Thanks

**Comment by lucasw** [comment]
The image_raw could have color information in it but in a bayer pattern, then it would be processed (by image_proc) to interpolate pixel values into rgb/bgr format.  That converted color image takes up 3x the bytes as the raw image if the input was 8bpp.

**Comment by gustavojoseleite** [comment]
Right, so the image_color has some processing for the pattern of color, for example, but doesn't have information about camera parameters just the image_color_rect have this correction, right?

Thanks for your reply @lucasw .
