### ISSUE TITLE
Issue in point_cloud_xyz launch file [ROS2]

### ISSUE THREAD

**Issue by hardesh** [ros-perception/image_pipeline#730]
Hi,

There's a typo on [this](https://github.com/ros-perception/image_pipeline/blob/1b6f868501ee0a753a3138bf31efd57c4054c5dc/depth_image_proc/launch/point_cloud_xyz.launch.py#L63) line. It should be [`image_rect`](https://github.com/ros-perception/image_pipeline/blob/1b6f868501ee0a753a3138bf31efd57c4054c5dc/depth_image_proc/src/point_cloud_xyz.cpp#L78) as mentioned in the code. 

I'd like to open up a PR to solve this. Let me know

**Comment by JWhitleyWork** [comment]
Please do.

**Comment by hardesh** [comment]
Okay cool :smiley:

**Comment by JWhitleyWork** [comment]
Closed by #732
