### ISSUE TITLE
Launch file issues for Stereo_image_proc

### ISSUE THREAD

**Issue by kraig9** [ros-perception/image_pipeline#734]
Using Galactic

Ubuntu 20.04

current launch file has many wrong params

after replacing with new param names problems seems to go away

fixes attached (replace file suffix)

[stereo_image_proc.launch.py.txt](https://github.com/ros-perception/image_pipeline/files/8142315/stereo_image_proc.launch.py.txt)

**Comment by JWhitleyWork** [comment]
@kraig9 If you are seeing issues and you have a fix, can you please create a pull request?

**Comment by mikeferguson** [comment]
The attached launch file look nothing like what is currently in rolling, so I have no idea what the "wrong params" are. Closing due to lack of feedback
