### ISSUE TITLE
ros2 branch fisheye_flags missing in constructor

### ISSUE THREAD

**Issue by javadan** [ros-perception/image_pipeline#738]
Hi, line 108 in camera_calibrator.py, fisheye_flags undefined

**Comment by javadan** [comment]
[#713](https://github.com/ros-perception/image_pipeline/issues/713)

**Comment by javadan** [comment]
[#724](https://github.com/ros-perception/image_pipeline/pull/724/commits/2a78a0aba5df5f7ebbfaec32c43dc769d14801f7)

**Comment by mikeferguson** [comment]
Assigning to myself - going to run through the various calibration issues in the next two weeks

**Comment by mikeferguson** [comment]
Appears fixed in https://github.com/ros-perception/image_pipeline/commit/2640ed1e0a9ad513b88ec4010b0b4fd857fb3ff0
