### ISSUE TITLE
CropDecimateNode Number Subscribers / image_view

### ISSUE THREAD

**Issue by mhubii** [ros-perception/image_pipeline#739]
Hi there, the `CropDecimateNode` won't process images unless the number of subscriber is > 0, see

https://github.com/ros-perception/image_pipeline/blob/3cc137863ab039aa1a1a2271e6df2d9622479089/image_proc/src/crop_decimate.cpp#L134

intuitively, this makes sense. However, if, for example, one subscribes via `ros2 run image_view image_view --ros-args --remap image:=/out/image_raw`, the number of subscribers remains 0. 

I believe this happens because `image_view` has a `image_transport::Subscriber`, see

https://github.com/ros-perception/image_pipeline/blob/3cc137863ab039aa1a1a2271e6df2d9622479089/image_view/include/image_view/image_view_node.hpp#L64

whereas `CropDecimateNode` has a `image_transport::CameraPublisher`, see

https://github.com/ros-perception/image_pipeline/blob/3cc137863ab039aa1a1a2271e6df2d9622479089/image_proc/include/image_proc/crop_decimate.hpp#L71

However, in `getNumSubscribers`, the max is returned

https://github.com/ros-perception/image_common/blob/40e0df25928950d757058302c29526667c385cbe/image_transport/src/camera_publisher.cpp#L99

Also, this error doesn't occur if one builds `image_transport` from source, but with the `foxy` distribution.

I don't know if this is a bug of the `image_view` node, or desired behavior. It just caused me a lot of trouble debugging my code, so I at least wanted to share this insight here.

**Comment by JWhitleyWork** [comment]
This is desired behavior to save the CPU cycles if there are no subscribers. With regard to `image_view`, I have seen this behavior before and I'm not exactly sure what causes it. If you find any sort of cause/fix, feel free to open a PR.

**Comment by mhubii** [comment]
thanks for the prompt response. This is no particular issue of `image_view`, but rather of `image_transport`. I created a minimal example to reproduce, see ros-perception/image_common#238
