### ISSUE TITLE
Issues with cv_bridge when using cameracalibrator.py in Indigo

### ISSUE THREAD

**Issue by angelmerino** [ros-perception/image_pipeline#74]
After updating to Ubuntu 14.04 and Indigo I'm not able to execute the camera_calibration.

With last version of opencv libraries (github repository master) python keeps looking for "cv.so". I have no issues with Hydro.

Also when using the repository installation of opencv (2.4.9) camera_calibration gives me this error:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/camera_calibration/cameracalibrator.py", line 68, in run
    self.function(m)
  File "/opt/ros/indigo/lib/camera_calibration/cameracalibrator.py", line 138, in handle_monocular
    drawable = self.c.handle_msg(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 749, in handle_msg
    gray = self.mkgray(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 262, in mkgray
    mono16 = self.br.imgmsg_to_cv(msg, "mono16")
AttributeError: CvBridge instance has no attribute 'imgmsg_to_cv'
```

I am trying to calibrate an Argos 3D Tof camera. Everything works in Hydro. Even when I try to execute:

```
rosrun camera_calibration cameracalibrator.py
```

I do not get any answer. It gets frozen. 

Reported in ROS answers: http://answers.ros.org/question/170971/issues-with-cv_bridge-when-using-cameracalibratorpy-in-indigo/
Report to bug tracker suggested.

**Comment by vrabaud** [comment]
yes, that's totally a bug: I removed the cv1 support (as it was marked as deprecated) and I did not update that package. Been very busy with ICRA but I am fixing it asap.

**Comment by vrabaud** [comment]
I will not have time to test until this weekend but the following is completely ported to cv2:
https://github.com/vrabaud/image_pipeline/tree/indigo
(feel free to try if you have time)

**Comment by angelmerino** [comment]
Thank you for your work.
I'm also kind of busy these days but I will try to test it.
