### ISSUE TITLE
ros2 version: image_rotate does not initialize the target and source _vectors in constructor

### ISSUE THREAD

**Issue by dcconner** [ros-perception/image_pipeline#740]
Need to add the following after onInit() call to update data; target_vector and source_vector default to zero

` 
  target_vector_.vector.x = config_.target_x;
  target_vector_.vector.y = config_.target_y;
  target_vector_.vector.z = config_.target_z;

  source_vector_.vector.x = config_.source_x;
  source_vector_.vector.y = config_.source_y;
  source_vector_.vector.z = config_.source_z;

`

**Comment by clalancette** [comment]
Can you please open a pull request with that change so we can review it?  Thanks.

**Comment by dcconner** [comment]
I verified compilation for image_rotate, but I went in another direction and developed a new node for ROS 2 I called image_flip that I present in PR #743 for review .  I'm not set up to fully test this PR
