### ISSUE TITLE
image rotate Resolution

### ISSUE THREAD

**Issue by Taysssir** [ros-perception/image_pipeline#741]
Hi, I'm using **image_rotate** package to rotate my camera stream. I got the stream rotated correctly but this change the resolution 

**Resolution Before Rotation**  : `/camera/image_raw`  : **640 x 480** 

**Resolution After Rotation**  : `/camera/rotated/image_raw` : **640 x 640** 

How can got the stream rotated without chagning resolution?
Any helps!
Thanks

**Comment by JWhitleyWork** [comment]
@Taysssir This can be changed with the `output_image_size` parameter. See documentation [here](https://github.com/ros-perception/image_pipeline/blob/aa6437b1979662c258e21ed1362e2038a4f9f590/image_rotate/cfg/ImageRotate.cfg#L57).

**Comment by ok-kewei** [comment]
@Taysssir probably you could use openCV2 to rotate without changing its resolution. Lemme know if you need help.
