### ISSUE TITLE
New release into Rolling

### ISSUE THREAD

**Issue by clalancette** [ros-perception/image_pipeline#742]
Currently depth_image_proc fails to build on Rolling: https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__depth_image_proc__ubuntu_jammy_amd64__binary/ .

The good news is that this issue is fixed in the latest HEAD of the `rolling` branch, so all we need here is a new release into Rolling.  @JWhitleyWork it looks like you did the previous release; do you mind doing another one?  If you don't have time, let me know and I can do the release instead.  Thanks!

**Comment by JWhitleyWork** [comment]
I actually need to do a little clean-up/convergence on branches on this repo. There are about 15 commits on the `rolling` branch that aren't on `ros2` and about the same that are on `ros2` but not on `rolling`. My plan to correct this is to rebase `rolling` on `ros2` as the intent is to have `ros2` support the released distros. Thoughts?

**Comment by clalancette** [comment]
> I actually need to do a little clean-up/convergence on branches on this repo. There are about 15 commits on the `rolling` branch that aren't on `ros2` and about the same that are on `ros2` but not on `rolling`. My plan to correct this is to rebase `rolling` on `ros2` as the intent is to have `ros2` support the released distros. Thoughts?

That seems reasonable to me.  For better or worse, that follows our conventions on other repositories.

**Comment by JWhitleyWork** [comment]
@clalancette Please review the rolling-rebase branch, if you could. Some of the changes from `ros2` and `rolling` affected the same lines so I had to resolve several conflicts as best I could, not knowing exactly what changes were important for each branch. If you find any mistakes, please feel free to do the rebase yourself and force-push it to `rolling`.

**Comment by clalancette** [comment]
I took a quick, non-exhaustive look at the merge, and things look generally reasonable.  So I'd suggest to go ahead and push the results of all of that to the `ros2` branch.

That said, running `colcon test` on the resulting output resulted in large numbers of test failures, mostly in cpplint and uncrustify but also in some other tests as well.  I'll suggest that we fix those, though maybe in a new PR.

**Comment by JWhitleyWork** [comment]
Base on the previous discussion, I'm assuming you meant `rolling`. The changes have been pushed there. I'm working on a PR to fix the testing failures now.

**Comment by clalancette** [comment]
> Base on the previous discussion, I'm assuming you meant `rolling`. The changes have been pushed there. I'm working on a PR to fix the testing failures now.

Earlier in the conversation you said:

```
My plan to correct this is to rebase rolling on ros2 as the intent is to have ros2 support the released distros.
```

So I assumed this would all be done on the `ros2` branch.  That said, I really don't care which branch is used to support Rolling releases, as long as it is consistent in https://github.com/ros/rosdistro/blob/f6fa0641e0a268b51a5b179c3b06ba34a3e22219/rolling/distribution.yaml#L1333-L1357 and https://github.com/ros2-gbp/image_pipeline-release/blob/f07b904d4cdd1c2488294e401c48c543250edda0/tracks.yaml#L101-L126 (which it currently is not).

**Comment by doisyg** [comment]
friendly ping here, as this package is my only workspace dependency not released to rolling/humble

**Comment by clalancette** [comment]
https://github.com/ros-perception/image_pipeline/pull/745 fixes the rest of the tests.  Once we get that in, we should be good to do a release here.

**Comment by clalancette** [comment]
@JWhitleyWork With the fixes now in, would you like to do a release, or should I?

**Comment by clalancette** [comment]
I'm going to go ahead and do a release here.

**Comment by clalancette** [comment]
This is now done in https://github.com/ros/rosdistro/pull/32952 , so I'm going to close this out.

**Comment by JWhitleyWork** [comment]
Thanks, @clalancette! Very sorry for the delay.

**Comment by chapulina** [comment]
Should this be released into Humble too? `Hpr` jobs are failing with `KeyError: "The cache has no package named 'ros-humble-image-pipeline'"`. The release probably came after the fork.

* https://github.com/ros2/variants/pull/34

**Comment by clalancette** [comment]
> Should this be released into Humble too? `Hpr` jobs are failing with `KeyError: "The cache has no package named 'ros-humble-image-pipeline'"`. The release probably came after the fork.

Yes, good point.  I'll go ahead and do that.

**Comment by clalancette** [comment]
Now done at https://github.com/ros/rosdistro/pull/33033 .
