### ISSUE TITLE
Point Cloud transformation error

### ISSUE THREAD

**Issue by costashatz** [ros-perception/image_pipeline#75]
Hello,

I am using **stereo_image_proc** to process data coming from a stereo system. When trying to visualize it in RVIZ I came across to the following issue: **The point cloud** _(pointcloud2 and pointcloud topics)_ **is not properly transformed**. See the following images:

**In gazebo:**
![pc_issue_gazebo](https://cloud.githubusercontent.com/assets/1283922/3115469/1744ac0e-e709-11e3-8e17-84c713713794.png)

**In RVIZ:**
![pc_issue_moveit](https://cloud.githubusercontent.com/assets/1283922/3115472/2044a638-e709-11e3-8023-6b9ed6eeb568.png)

Any ideas?

**P.S.: The cameras seem properly transformed.** See images below:

**Left:**
![left](https://cloud.githubusercontent.com/assets/1283922/3115534/eef65dbe-e709-11e3-8ae9-793dcd54bb60.jpg)

**Right:**
![right](https://cloud.githubusercontent.com/assets/1283922/3115539/fafae6fc-e709-11e3-8d06-c4366250d28e.jpg)

**Comment by vrabaud** [comment]
On which ROS distro ? Do you have an intuition of what is wrong ? From your screenshot, there is obviously a transform problem but it seems the point cloud is wrong too no ? Like it's squished along a dimension or something.

**Comment by costashatz** [comment]
I am using ROS Hydro.. I believe the point cloud is correct. Maybe the image is not that clear.

As for the problem, I know that stereo_image_proc produces the point cloud in different axes (x right, y down, z forward) from what ROS generally has (x forward, y left, z up). Do I need to attach a frame with these axes to the camera in order for the point cloud to be transformed correctly?

**Comment by costashatz** [comment]
> > Do I need to attach a frame with these axes to the camera in order for the point cloud to be transformed correctly?

That's what solved my issues.. I will make some tests and when I'm certain this is it, I will close this issue.

Cheers
