### ISSUE TITLE
camera_calibration remapping of left and right camera topics ROS2

### ISSUE THREAD

**Issue by wouter-heerwegh** [ros-perception/image_pipeline#754]
Hi,

When I try to add left and right arguments, I get warnings telling me to use --ros-args --remap. But when I do, the arguments are not used due to [this line](https://github.com/ros-perception/image_pipeline/blob/3cc137863ab039aa1a1a2271e6df2d9622479089/camera_calibration/src/camera_calibration/nodes/cameracalibrator.py#L87). It thus looks for hardcoded names of service topics, which it cannot find and does nothing.

Is this something to be fixed in the future?

**Comment by JWhitleyWork** [comment]
Fixed by #755. (Please re-open if this is incorrect)
