### ISSUE TITLE
camera_calibration: Move approxsync.py to ros_comm

### ISSUE THREAD

**Issue by jbohren** [ros-perception/image_pipeline#76]
The python [approximate time synchronizer](https://github.com/ros-perception/image_pipeline/blob/indigo/camera_calibration/src/camera_calibration/approxsync.py) should really be moved into [ros_comm](https://github.com/ros/ros_comm/blob/indigo-devel/utilities/message_filters/src/message_filters/__init__.py)

@colincsl

**Comment by jbohren** [comment]
https://github.com/ros/ros_comm/issues/424

**Comment by vrabaud** [comment]
before indigo I guess ?

**Comment by vrabaud** [comment]
That file should be removed and it should use the official Python one at:
https://github.com/ros/ros_comm/blob/indigo-devel/utilities/message_filters/src/message_filters/__init__.py#L101

**Comment by colincsl** [comment]
@vrabaud, the one you pointed to requires that all timestamps have the same time. The approximate time synchronizer has a 'slop' value so that time stamps don't need to be exactly the same.

**Comment by vrabaud** [comment]
@colincsl  yop, I had not seen that thx. The MR is in https://github.com/ros/ros_comm/issues/424 , please confirm it suits your needs.
