### ISSUE TITLE
Camera Calibration "window is not responding"

### ISSUE THREAD

**Issue by ijnek** [ros-perception/image_pipeline#762]
While running camera calibration, the cameracalibration window is reported unresponsive in Ubuntu22.04, and perhaps older Ubuntu distros too:

![image](https://user-images.githubusercontent.com/18237662/179713427-d4c11a80-568f-4bb4-8022-19252104e228.png)

This is an issue because it usually indicates a crashed program, but here, it's actually just taking time to calibrate.

Are there some easy workarounds to prevent this window from showing up, and a nice feature would be to have something like a progress bar for user feedback. (I understand that no one has the time for the nice features though).

**Comment by mikeferguson** [comment]
Looks like fix was merged in linked PR
