### ISSUE TITLE
catkin_make failed

### ISSUE THREAD

**Issue by qibo02** [ros-perception/image_pipeline#763]
hi can you help me with this problem..
![image](https://user-images.githubusercontent.com/104100699/180403239-0a447e40-3196-4e01-933b-5d035aa581ee.png)

**Comment by JWhitleyWork** [comment]
Did you install the dependencies with `rosdep` or manually before trying to build? Additionally, you can also just install the binaries with `apt` rather than building the package from source.

**Comment by fbaygul** [comment]
http://wiki.ros.org/rosdep

run this command "rosdep install --from-paths src --ignore-src -r -y" in your ws
