### ISSUE TITLE
Disparity maps are so bad for stereo cameras

### ISSUE THREAD

**Issue by farhad-dalirani** [ros-perception/image_pipeline#765]
Hello, 

These images are from my left and right cameras. The third image is a disparity map. (Images are 4K)

I generated it with these commands:

```
ROS_NAMESPACE=ros_basler_stereo rosrun stereo_image_proc stereo_image_proc _approximate_sync:=True
```
and
```
rosrun image_view stereo_view stereo:=/ros_basler_stereo image:=image_raw _approximate_sync:=True _queue_size:=800
```
![Screenshot from 2022-07-24 00-11-17](https://user-images.githubusercontent.com/65308831/180631923-b870a979-66b4-4352-a40d-0d752184a305.png)

**Comment by lidarmansiwon** [comment]
I have same lssue. did you solve that issue? 
![8](https://user-images.githubusercontent.com/117976120/215970903-a7dae16a-cf90-43d2-be33-c182989dda56.png)

**Comment by farhad-dalirani** [comment]
There can be several methods, three of them:

1- change the parameter for creating a depth map
2- change the distance between the two cameras. For different depths, different baselines obtain different results. For example, inside a small room, a baseline of 10 cm can be enough. However, for cars on the streets, it can be 20 cm.
3- Maybe your environment does not have enough features. Therefore, the matching fails.

**Comment by lidarmansiwon** [comment]
> There can be several methods, three of them:
> 
> 1- change the parameter for creating a depth map 2- change the distance between the two cameras. For different depths, different baselines obtain different results. For example, inside a small room, a baseline of 10 cm can be enough. However, for cars on the streets, it can be 20 cm. 3- Maybe your environment does not have enough features. Therefore, the matching fails.

Thank you for your quick reply!
Can i use [rosrun rqt_reconfigure rqt_reconfigure] to change the parameter?? how can i change parameter for a depth map..?

**Comment by mikeferguson** [comment]
This doesn't appear to really be an actionable ticket - all of the suggestions are about the configuration and hardware setup rather than some intrinsic problem in the code.
