### ISSUE TITLE
Question: Compiling with optimization

### ISSUE THREAD

**Issue by eggerdo** [ros-perception/image_pipeline#77]
I am trying to compile image_pipeline and in particular depth_image_proc from source for hydro (without any modifications). I tried it with `catkin_make` and `catkin_make -DCMAKE_BUILD_TYPE=Release` but in each case when I run it in conjunction with openni2_launch I only get half the message rate that I achieve when using the version from apt.
How do I need to compile it to get the same performance? Are there any compile options for catkin to optimize the performance?

**Comment by vrabaud** [comment]
that probably more belong to ros.answers but I don't see what would be slow. Is your CPU completely used ? What other packages do you have in your workspace ?

**Comment by eggerdo** [comment]
Ok sorry, I thought it more fits here than at ros.answers, but I will post my questions there next time. I don't know what was going on, but now I cleared my workspace, compiled everything again with release and now it works, even slightly faster than the version on apt. So sorry for the bother, but thanks for your answer nevertheless.

**Comment by vrabaud** [comment]
cool ! Here is fine too, but just provide a bit more info so that I can help you next time :)
Indigo will be even a bit faster !
