### ISSUE TITLE
'std::runtime_error', what() can't subtract times with different time sources 1 = 2

### ISSUE THREAD

**Issue by ddwy** [ros-perception/image_pipeline#774]
When I run the following command, the following error will appear:

command:
ros2 run image_view video_recorder --ros-args --remap image:=/color/preview/image

occur error:
terminate called after throwing an instance of 'std::runtime_error'
what(): can't subtract times with different time sources [1 != 2]

**Comment by mikeferguson** [comment]
Which distro/version are you using? It looks like #675 was intended to fix this issue

**Comment by mikeferguson** [comment]
Closing due to lack of response and what appears to be fix in codebase
