### ISSUE TITLE
Release for ROS1 Noetic?

### ISSUE THREAD

**Issue by furushchev** [ros-perception/image_pipeline#778]
There are some changes from the last release https://github.com/ros-perception/image_pipeline/compare/1.16.0...noetic
I think it's time to release the new version.
@JWhitleyWork

**Comment by furushchev** [comment]
@JWhitleyWork Ping to maintainer.

**Comment by JWhitleyWork** [comment]
Sorry for the delay. Release is now pending: https://github.com/ros/rosdistro/pull/34979

**Comment by furushchev** [comment]
@JWhitleyWork No worries! Thank you for your work!!
