### ISSUE TITLE
ros2 foxy image_view extract_images transport param always is --ros-args_sub

### ISSUE THREAD

**Issue by lucasrj** [ros-perception/image_pipeline#779]
then i tray to use the extractor in my luanchfile i allwais get an error 

'what():  Unable to load plugin for transport 'image_transport/--ros-args_sub', error string:'

but if change name of transport to test in the code works

[launch.log with error](https://github.com/ros-perception/image_pipeline/files/9724773/launch.log)
[launch.log after change](https://github.com/ros-perception/image_pipeline/files/9724779/launch.log)
[image_extractor.launch](https://github.com/ros-perception/image_pipeline/files/9724786/image_extractor.launch.txt)

**Comment by mikeferguson** [comment]
Possibly same cause as https://github.com/ros-perception/image_pipeline/issues/824?

**Comment by mikeferguson** [comment]
Foxy is EOL - and image_transport has had inconsistent support - support is now consistently addressed in rolling and will be part of Jazzy
