### ISSUE TITLE
Calibration not committed to camera properly

### ISSUE THREAD

**Issue by alyychan** [ros-perception/image_pipeline#78]
When I did rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image_raw camera:=/usb_cam,the calibration did not seem to commit to the camera properly. 

rosnode echo /usb_cam/camera_info gave me calibration data that did not correspond with the data from the actual calibration

**Comment by vrabaud** [comment]
thx, which version of ROS are you using ?

**Comment by alyychan** [comment]
Im using Hydro

**Comment by vrabaud** [comment]
What instructions did you run to get the set_camera_info service running ?

**Comment by alyychan** [comment]
I dont think I did that. I just ran the camera driver node (rosrun usb_cam usb_cam_node)

**Comment by vrabaud** [comment]
this is not a bug from image_pipeline, please follow https://github.com/bosch-ros-pkg/usb_cam/pull/13
