### ISSUE TITLE
Can depth_image_proc/register work with mono8 images?

### ISSUE THREAD

**Issue by TankyFranky** [ros-perception/image_pipeline#787]
Does depth_image_proc/register have to specifically be subscribed to a RGB image? The outline on [ros.org](http://wiki.ros.org/depth_image_proc#depth_image_proc.2Fregister) specifies an RGB image topic but then lists the `sensor_msgs/CameraInfo` topic for `rgb/camera_info`.

I would like to register my depth image with a mono8 image from an adjacent camera.

The register nodelet subscribes succesfully to `depth/camera_info` and `depth/image_rect` but will not subscribe to `rgb/camera_info`.

![Screenshot from 2022-12-07 17-46-10](https://user-images.githubusercontent.com/43577151/206313218-011329c3-a9b5-442a-99a3-bacb2a797de8.png)

You can see that the nodelet is unable to subscribe to `rgb/camera_info`.

Here is my launch file:

```
<launch>
  <node pkg="nodelet" type="nodelet" name="nodelet_manager" args="manager" />

  <node pkg="nodelet" type="nodelet" name="nodelet1"
        args="load depth_image_proc/register nodelet_manager">
    <remap from="rbg/camera_info"         to="/spot/depth/left/camera_info"/>
    <remap from="depth/camera_info"         to="/spot/depth/back/camera_info"/>
    <remap from="depth/image_rect"       to="/spot/depth/back/image"/>
  </node>
</launch>
```

**Comment by mikeferguson** [comment]
As far as I can see, there is no limitation on what type of image the "rgb" is - we don't use the image encoding - just the intrinsics of the camera_info message.

In your launch file - you have "rbg/camera_info" - it should be rgb not rbg (the order is wrong) - thus your remap isn't doing what you think
