### ISSUE TITLE
Which are supported image formats to register depth image?

### ISSUE THREAD

**Issue by sagardhatrak** [ros-perception/image_pipeline#794]
Which are the supported image formats for depth_image_proc/register?
How to convert depth image from mono16 to different formats supported to depth_image_proc/register?

**Comment by mikeferguson** [comment]
The two formats that are accepted are the ones commonly output by ROS camera drivers:

 * 16UC1 - which is common for Kinect-like devices. The 16-bit unsigned value is interpreted as being in millimeters.
 * 32FC1 - the 32-bit floating point value is expected to be in meters.

There is also the convert_metric node - which currently can be used to convert 16UC1 into 32FC1 (and vice versa - I have no idea exactly why this node exists with just those two options).

Going to add this to our documentation as part of migration off wiki.ros.org
