### ISSUE TITLE
image_view/camera_calibration cannot display mono16

### ISSUE THREAD

**Issue by han88** [ros-perception/image_pipeline#796]
Hi Im trying to calibrate my orbbec astra mini depth camera running with this  driver (https://github.com/orbbec/ros_astra_camera). The rgb calibration worked without problems, but for the ir stream the image_view/calibration window just show a black display without any error messages. camera/ir/image_raw  topic encoding is mono16! In rviz i can see the ir stream...
image_view throws this error:
ageView.callback_image() while trying to convert image from 'mono16' to 'rgb8' an exception was thrown (Image is wrongly formed: step < width * byte_depth * num_channels  or  640 != 640 * 2 * 1)
Thanks

**Comment by han88** [comment]
managed the depth calibration, wasn't the issue of display error in image_view...

**Comment by foxydevelby** [comment]
> managed the depth calibration, wasn't the issue of display error in image_view...

Hi @han88, how did you resolved your issue, I have the same. no errors but the qt window cannot display the IR stream (mono16)

**Comment by han88** [comment]
Hi I had that issue while calibration of the astra mini camera...there is
now an tutorial in the readme file of the ros_asta_carmera package..

Seifert

foxydevelby ***@***.***> schrieb am Mi., 26. Apr. 2023, 04:43:
