### ISSUE TITLE
Stereo calibration without horizontal/vertical alignment restriction

### ISSUE THREAD

**Issue by erinline** [ros-perception/image_pipeline#798]
Is there a way to use the stereo calibration tool for general camera rigs (neither horizontally nor vertically aligned)? 

I have two statically arranged cameras, with different intrinsic parameters as well, that I want to have a pixel transform between so I can perform computations combining multiple cameras' images. They are not directly horizontal or vertical with respect to each other, so the stereo calibration tool appears not to be applicable. However, I have written my own calibration script and it is not performing as well as I'd like either, due to missing the robust checks included in this tool. Rather than rewrite the entire tool, I'm hoping there is a simple modification I can make to use this tool for my camera setup.

**Comment by mikeferguson** [comment]
This is pretty open ended - I think it would be better suited to https://robotics.stackexchange.com
