### ISSUE TITLE
stereo_view_node.cpp prints out a deprecated command

### ISSUE THREAD

**Issue by dschlee** [ros-perception/image_pipeline#799]
In the branch `foxy` in the file `image_view/src/stereo_view_node.cpp` in the method `checkInputSynchronized()` the following warning gets printed:\
`Does rosnode info %s show any connections?`\
The command `rosnode info` is deprecated in ROS2 Foxy. The correct command should be `ros2 node info`.

**Comment by mikeferguson** [comment]
Fixed in rolling (not sure when - but commands are up to date)
