### ISSUE TITLE
image_saver's subsription of camera info

### ISSUE THREAD

**Issue by prclibo** [ros-perception/image_pipeline#80]
Hi, I started learning ROS recently and was using image_saver to collect some image data. I found the following code from image_saver.cpp:

  std::string topic = nh.resolveName("image");
  image_transport::CameraSubscriber sub_camera = it.subscribeCamera(topic, 1, &callback);
  image_transport::Subscriber sub_image = it.subscribe(topic, 1,
                           boost::bind(callback, _1, sensor_msgs::CameraInfoConstPtr()));

I am not very sure about how this works but I guess sub_camera should subscribe something like "/camera/camera_info". For me currently image_saver saves twice images than camera info. The images should be duplicated.

**Comment by vrabaud** [comment]
Depending on whether the topic you give is a CameraInfo or an image, it is going to save one or the other.
I am not sure I understand what is happening with you: you have an image that is being saved twice ?

**Comment by prclibo** [comment]
yea, both sub_camera and sub_image are subscribing to the topic of /camera/image_raw, so the callback is invoked twice and saves the image twice for each image. Just wanna suggest a small fix of making sub_camera subscribe "/camera/camera_info", rather than topic which is /camera/image_raw.
