### ISSUE TITLE
image_rect_color is delayed

### ISSUE THREAD

**Issue by luisbruegelhka** [ros-perception/image_pipeline#801]
Hello, 
I am using the image_pipeline-package on a Raspberry Pi 4 Modell B with Ros2 Humble.
When i undistort the camera stream with the image_proc package, i get a massiv delay on the image_rect_color.
The images are still published with the same frequency as image_raw, but are delayed about half a second.

Does anyone know why thats the case?

Thanks for your replies.

**Comment by mikeferguson** [comment]
Please post questions like this to https://robotics.stackexchange.com
