### ISSUE TITLE
There is nothing happen when i run camera_calibration cameracalibration,no 'display' window.

### ISSUE THREAD

**Issue by xiaowei0507** [ros-perception/image_pipeline#804]
![image](https://user-images.githubusercontent.com/83441140/223024080-4499a241-0037-4b8f-b481-5f23757b199f.png)
Could you please give some advice?

**Comment by xiaowei0507** [comment]
In ubuntu20.04,foxy.

**Comment by mikeferguson** [comment]
Foxy is EOL. I'd also recommend trying https://robotics.stackexchange.com for debugging help (there are many more folks over there on a regular basis)
