### ISSUE TITLE
[image_view] is color correction still required?

### ISSUE THREAD

**Issue by MyronRodrigues-StreetDrone** [ros-perception/image_pipeline#810]
I'm using ros humble and have the R and B colors flipped even though my image has correct encoding `rgb8`. The colors look right when seen from cv::imshow()

Color conversion on line 190 from branch `humble` in [image_pipeline/image_view/src/image_view_node.cpp](https://github.com/ros-perception/image_pipeline/blob/humble/image_view/src/image_view_node.cpp), is still required?

```cpp 
queued_image_.set(
  cv_bridge::cvtColorForDisplay(
    cv_bridge::toCvShare(msg), "bgr8", options));
```

**Comment by mikeferguson** [comment]
The real fix here is that we should be reading the encoding from the image message - and defaulting to bgr8 (the preferred) if no encoding is found - https://github.com/ros-perception/image_pipeline/pull/850 fixes that
