### ISSUE TITLE
New publisher discovered on topic '/camera/depth/color/points', offering incompatible QoS.

### ISSUE THREAD

**Issue by kenloumixx** [ros-perception/image_pipeline#827]
Hello, thank you for sharing the marvelous package :) 

I use depth_image_proc::point_cloud_xyz_node in ROS2 and want to visualize the pointcloud in rviz2. 

However, the pointcloud does not appear, and it shows the warning 
`[WARN] [1688452110.335103058] [rviz]: New publisher discovered on topic '/camera/depth/color/points', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
`
I also look [this conversation](https://github.com/ros-perception/image_pipeline/pull/814#issuecomment-1549147011) and changed the QOS from RELIABLE to BEST_EFFORT and then the below error spilled out without no change.
```
[INFO] [1688452612.129694289] [rviz]: Message Filter dropping message: frame 'camera_color_optical_frame' at time 1688452603.371 for reason 'discarding message because the queue is full'
[INFO] [1688452613.172665949] [rviz]: Message Filter dropping message: frame 'camera_color_optical_frame' at time 1688452603.539 for reason 'discarding message because the queue is full'
[INFO] [1688452615.418285755] [rviz]: Message Filter dropping message: frame 'camera_color_optical_frame' at time 1688452603.940 for reason 'discarding message because the queue is full'
```
Since I align the depth image to color frame, the remapping was 
```
(/camera_info, /camera/aligned_depth_to_color/camera_info)
(/image_rect, /camera_aligned_depth_to_color/image_raw)
(/points, /camera/depth/color/points)
```

May I ask how can I solve this error? thank you!

**Comment by mikeferguson** [comment]
The message filter issues are TF-related - you don't have TF data for 'camera_color_optical_frame'. If you need to follow up on this - please use https://robotics.stackexchange.com
