### ISSUE TITLE
image_view error on Ros Indigo - Ubuntu 13.10

### ISSUE THREAD

**Issue by TSC21** [ros-perception/image_pipeline#83]
I get the following error when launching image_view to get image from px4flow camera using rosrun image_view image_view image:=/px4flow/camera_image:

(image_view:43558): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GtkWidget'

(image_view:43558): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(image_view:43558): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

This error was also reported in answers.ros.org - http://answers.ros.org/question/35784/image_view-giving-glib-errors-and-not-displaying-a-window/

**Comment by vrabaud** [comment]
I do not have any problem in Ubuntu 14.04 . Does it crash right up ? Is it something you compile yourself ?

**Comment by TSC21** [comment]
It crashes right up. No window appears.
Not something I compiled. Just followed http://wiki.ros.org/px4flow_node.
And as you can see here http://answers.ros.org/question/35784/image_view-giving-glib-errors-and-not-displaying-a-window/, I'm not the only one with this problem.

**Comment by vrabaud** [comment]
I read that question. Does it crash right up ? Or does it freeze sometimes ?

**Comment by TSC21** [comment]
It stays freezed. Doesn't return the command line.

init done 
opengl support available 

(image_view:3468): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GtkWidget'

(image_view:3468): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(image_view:3468): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

**Comment by vrabaud** [comment]
ok, that code needs a rewrite: it uses startWindowThread which is not good, and not even working on different environments, cf: http://answers.ros.org/question/11934/image_view-disparity_view-stereo_view-osx/
Will try to fix that this weekend.

**Comment by TSC21** [comment]
So what needs correction? px4flow_node or image_view?

**Comment by vrabaud** [comment]
Hi, could you please check out my version here : https://github.com/vrabaud/image_pipeline/
I changed the behavior so that you can only quit by pressing 'q' but at least, it is GTK agnostic.

**Comment by TSC21** [comment]
Should I catkin_make in my WS or do a catkin_make -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo install? Any of it seems to resolve the problem, as I'm getting the same problem. I cloned the indigo branch by the way.

**Comment by vrabaud** [comment]
catkin_make and then run the version from your workspace after sourcing the setup.sh.
Your sentence says both that it solves the problem and not. Which one is it ? :)

**Comment by vrabaud** [comment]
I removed the GTK code in trunk of Indigo, does that help your case ? (I have not released it yet though)

**Comment by vrabaud** [comment]
any news with the latest release ? I fixed some other crashes related to display.

**Comment by vrabaud** [comment]
Saucy will soon not be supported by ROS anyway. Please re-open if you get the same on Trusty or above.
