### ISSUE TITLE
model_.rectifyImage() memory leak issue

### ISSUE THREAD

**Issue by swampblimps** [ros-perception/image_pipeline#831]
Anyone have any idea about the line "model_.rectifyImage(image, rect, interpolation);" would cause memory leak for ROS 2 image-proc package?

**Comment by mikeferguson** [comment]
I don't see any clear cause here - but if there is a memory leak in rectifyImage() then that should probably be filed to https://github.com/ros-perception/vision_opencv as that is where the image_geometry package is located (which model_ is from).
