### ISSUE TITLE
NameError: name 'CAMERA_MODEL' is not defined

### ISSUE THREAD

**Issue by haormj** [ros-perception/image_pipeline#833]
- branch: foxy
- ros2 run camera_calibration cameracalibrator --size 6x8 --square 0.02 --ros-args -r image:=/front_camera/image_raw -p camera:=/front_camera
- camera type fisheye
- then prompt "NameError: name 'CAMERA_MODEL' is not defined"

**Comment by mikeferguson** [comment]
This is fixed in humble and later, so all current ROS 2 releases
