### ISSUE TITLE
Unable to get the fps of image_rect_color using image_proc

### ISSUE THREAD

**Issue by sunilbodla** [ros-perception/image_pipeline#842]
I want to rectify the topics of tof camera having depth topics that is depth/image and camera_info having different timestamp.

when I used the image_proc package to get the image_rect_color of both of these depth camera topics, i did not received any fps of image_rect_color.

**Comment by mikeferguson** [comment]
This is better suited to [robotics.stackexhange.com](https://robotics.stackexchange.com)
