### ISSUE TITLE
Camera calibration doesn't work outdoors

### ISSUE THREAD

**Issue by trainman419** [ros-perception/image_pipeline#90]
Works in our garage, doesn't work outside. I'm so confused.

Log file from outdoors: http://driving.stanford.edu/data/fleaL_cal-07-22-2014_19-48-50.cameras.bag

**Comment by mikeferguson** [comment]
Define "doesn't work" -- does it not find the checkerboards, or does the checkerboard get found but it refuses to converge -- or does it converge but it's totally wrong -- or?

**Comment by trainman419** [comment]
It doesn't detect the checkerboard corners at all.

**Comment by vrabaud** [comment]
Hey, for some reason the fast option makes it fail. The following works for me:

```
rosrun  camera_calibration cameracalibrator.py image:=/driving/fleaL/image_raw --size 12x8 --square 0.108 --disable_calib_cb_fast_check
```
