### ISSUE TITLE
range_max sensor value introduced but not used

### ISSUE THREAD

**Issue by S-A-M-J** [ros-perception/image_pipeline#924]
I was wondering why in point_cloud_xyz.cpp in line 112 convertDepth is called but there is no way to set the max_sensor range that is part of the function based on a parameter given to the nodelet. I mean why implement the max sensor range variable and then not make it usable?

The option to set this parameter when calling convertDepth is not used in a single nodelet definition and would be a really useful tool for map generation. Perhaps someone can shed some light on that choice.

**Comment by mikeferguson** [comment]
I'm thinking this is some sort of oversight, but it's likely nobody knows why at this point.

A PR that adds a parameter to enable this behavior would be accepted (we shouldn't change the default behavior).

**Comment by PhilippPolterauer** [comment]
I tried tackling this issue with the PR #943. I would highly appreciate if you could have a look, and discuss with me some further steps.
