### ISSUE TITLE
cameracalibrator.py not installed on Indigo

### ISSUE THREAD

**Issue by rctoris** [ros-perception/image_pipeline#93]
It looks like `cameracalibrator.py` isn't being installed properly on Indigo. 

`rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.025 image:=/usb_cam/image_raw camera:=/usb_cam`
`[rosrun] Couldn't find executable named cameracalibrator.py below /opt/ros/indigo/share/camera_calibration`

Building from source and running from `source devel/setup.bash` works but running from `source install/setup.bash` does not.

**Comment by vrabaud** [comment]
that was a huge mistake ! thx, I am releasing it right now.

**Comment by rctoris** [comment]
Thanks!

**Comment by CaptD** [comment]
Hi, I still have this problem. Which branch has the fix? Thanks.

**Comment by k-okada** [comment]
it should be fixed, please confirm again.

```
$ aptitude show ros-indigo-camera-calibration 
Package: ros-indigo-camera-calibration   
State: installed
Automatically installed: yes
Version: 1.12.19-0trusty-20170313-093807-0700
Priority: extra
Section: misc
Maintainer: Vincent Rabaud <vincent.rabaud@gmail.com>
Architecture: amd64
Uncompressed Size: 213 k
Depends: ros-indigo-cv-bridge, ros-indigo-image-geometry, ros-indigo-message-filters, ros-indigo-rospy,
         ros-indigo-sensor-msgs, ros-indigo-std-srvs
Conflicts: ros-indigo-camera-calibration
Description: camera_calibration allows easy calibration of monocular or stereo cameras using a checkerboard calibration target.
 
Homepage: http://www.ros.org/wiki/camera_calibration

$ dpkg -L ros-indigo-camera-calibration | grep cameracalib
/opt/ros/indigo/lib/camera_calibration/cameracalibrator.py
```
