### ISSUE TITLE
image_proc / image_proc.launch.py not working with namespace for ROS2 Iron

### ISSUE THREAD

**Issue by aaalloc** [ros-perception/image_pipeline#952]
Hey, the current version of  ```image_proc.launch.py``` on iron branch is not updated like on the rolling branch, so it is not possible to run ```image_proc.launch.py``` like this ```ros2 launch image_proc image_proc.launch.py namespace:=my_camera``` as stated on the documentation https://docs.ros.org/en/rolling/p/image_proc/tutorials.html#using-image-proc-launch-file

https://github.com/ros-perception/image_pipeline/blame/rolling/image_proc/launch/image_proc.launch.py#L46

https://github.com/ros-perception/image_pipeline/blame/iron/image_proc/launch/image_proc.launch.py

**Comment by mikeferguson** [comment]
Launch file changes backported to Iron (note that some other changes, like the camera_info remapping will NOT be back ported - because these could possibly break anyone who worked around them)
