### ISSUE TITLE
No image shown when using image_view

### ISSUE THREAD

**Issue by thiagoblanco99** [ros-perception/image_pipeline#958]
I am working with ros2 humble and I was currently using image_view to open disparity images. Today when executing the node, the windows the usually pops up wasn't there, and I tried to open stereo_view and image_view and none of them where showing the image. 
have any idea what is going on ?

**Comment by CursedRock17** [comment]
What are the steps to recreate? Was this behavior normal beforehand, then now the window doesn't pop up?

**Comment by thiagoblanco99** [comment]
I just was not doing the things correctly, I made a ros bag with a very similar name but not the same :( 
Thank you for the answer :+1:
