### ISSUE TITLE
RVIZ not showing point cloud

### ISSUE THREAD

**Issue by mhmd-mst** [ros-perception/image_pipeline#960]
I am using ROS Noetic on Ubuntu 20.04, on wsl2, I have a bag file that is publishing the depth_images and the  corresponding intrinsics, then using depth_image_proc/point_cloud_xyz I publish /points, while using rostopic echo /points shows an output, on RVIZ with status ok and messages received I am not seeing the pointcloud, then I trying using octomap_server subscribed to the /points and I get octree empty, there seems something wrong witht the  point cloud I guess but I do not know why? I attached below the rviz and the tf_tree, the frame_id camera is connect to base camera by a static transform publisher .
![rviz](https://github.com/ros-perception/image_pipeline/assets/37877095/3a54e77d-bb8e-4f97-afc5-ae310f7c0a6b)
![frames](https://github.com/ros-perception/image_pipeline/assets/37877095/debf3890-54dd-4074-8587-354e8a1f8925)

**Comment by mikeferguson** [comment]
Please post to https://robotics.stackexchange.com - you're going to find quite a bit more help there (the ROS 1 branches here are really barely maintained - the active maintainers are all focused on ROS 2)
