### ISSUE TITLE
Making camera calibration code more maintainable

### ISSUE THREAD

**Issue by MRo47** [ros-perception/image_pipeline#973]
- `calibrator.py` file is almost 1.5K lines long and difficult to navigate.
- This could break dependencies? I'd like to know more if this is true.
- Ive fixed the imports in the remaining files.

Have something [ready](https://github.com/MRo47/image_pipeline/tree/iron-separate-calib-types/camera_calibration/src/camera_calibration) but thought it would be better to discuss if its even required.

**Comment by ahcorde** [comment]
Can you open the PR ? It's better to discuss this there.

**Comment by MyronRodrigues-StreetDrone** [comment]
sure thing!
